
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
/**
 * Model Authenticator
 * 
 */
export type Authenticator = Prisma.AuthenticatorModel
/**
 * Model Chama
 * 
 */
export type Chama = Prisma.ChamaModel
/**
 * Model ChamaLoan
 * 
 */
export type ChamaLoan = Prisma.ChamaLoanModel
/**
 * Model Projects
 * 
 */
export type Projects = Prisma.ProjectsModel
/**
 * Model Member
 * 
 */
export type Member = Prisma.MemberModel
/**
 * Model BalanceSheet
 * 
 */
export type BalanceSheet = Prisma.BalanceSheetModel
/**
 * Model Saving
 * 
 */
export type Saving = Prisma.SavingModel
/**
 * Model Deduction
 * 
 */
export type Deduction = Prisma.DeductionModel
/**
 * Model Loan
 * 
 */
export type Loan = Prisma.LoanModel
/**
 * Model ShortLoan
 * 
 */
export type ShortLoan = Prisma.ShortLoanModel
/**
 * Model Penalty
 * 
 */
export type Penalty = Prisma.PenaltyModel
/**
 * Model Dividend
 * 
 */
export type Dividend = Prisma.DividendModel
