
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  MEMBER: 'MEMBER',
  ADMIN: 'ADMIN',
  CHAIRMAN: 'CHAIRMAN',
  SECRETARY: 'SECRETARY',
  VICE_CHAIRMAN: 'VICE_CHAIRMAN',
  TREASURER: 'TREASURER'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const TransactionStatus = {
  PENDING: 'PENDING',
  INCOMPLETE: 'INCOMPLETE',
  COMPLETED: 'COMPLETED'
} as const

export type TransactionStatus = (typeof TransactionStatus)[keyof typeof TransactionStatus]


export const LoanType = {
  LONG_TERM: 'LONG_TERM',
  SHORT_TERM: 'SHORT_TERM'
} as const

export type LoanType = (typeof LoanType)[keyof typeof LoanType]
