
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ChamaLoan` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ChamaLoan
 * 
 */
export type ChamaLoanModel = runtime.Types.Result.DefaultSelection<Prisma.$ChamaLoanPayload>

export type AggregateChamaLoan = {
  _count: ChamaLoanCountAggregateOutputType | null
  _avg: ChamaLoanAvgAggregateOutputType | null
  _sum: ChamaLoanSumAggregateOutputType | null
  _min: ChamaLoanMinAggregateOutputType | null
  _max: ChamaLoanMaxAggregateOutputType | null
}

export type ChamaLoanAvgAggregateOutputType = {
  loanAmount: number | null
  interest: number | null
  termMonths: number | null
}

export type ChamaLoanSumAggregateOutputType = {
  loanAmount: number | null
  interest: number | null
  termMonths: number | null
}

export type ChamaLoanMinAggregateOutputType = {
  id: string | null
  chamaId: string | null
  lender: string | null
  loanAmount: number | null
  interest: number | null
  termMonths: number | null
  dueDate: Date | null
  paymentDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ChamaLoanMaxAggregateOutputType = {
  id: string | null
  chamaId: string | null
  lender: string | null
  loanAmount: number | null
  interest: number | null
  termMonths: number | null
  dueDate: Date | null
  paymentDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ChamaLoanCountAggregateOutputType = {
  id: number
  chamaId: number
  lender: number
  loanAmount: number
  interest: number
  termMonths: number
  dueDate: number
  paymentDate: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ChamaLoanAvgAggregateInputType = {
  loanAmount?: true
  interest?: true
  termMonths?: true
}

export type ChamaLoanSumAggregateInputType = {
  loanAmount?: true
  interest?: true
  termMonths?: true
}

export type ChamaLoanMinAggregateInputType = {
  id?: true
  chamaId?: true
  lender?: true
  loanAmount?: true
  interest?: true
  termMonths?: true
  dueDate?: true
  paymentDate?: true
  createdAt?: true
  updatedAt?: true
}

export type ChamaLoanMaxAggregateInputType = {
  id?: true
  chamaId?: true
  lender?: true
  loanAmount?: true
  interest?: true
  termMonths?: true
  dueDate?: true
  paymentDate?: true
  createdAt?: true
  updatedAt?: true
}

export type ChamaLoanCountAggregateInputType = {
  id?: true
  chamaId?: true
  lender?: true
  loanAmount?: true
  interest?: true
  termMonths?: true
  dueDate?: true
  paymentDate?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ChamaLoanAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ChamaLoan to aggregate.
   */
  where?: Prisma.ChamaLoanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChamaLoans to fetch.
   */
  orderBy?: Prisma.ChamaLoanOrderByWithRelationInput | Prisma.ChamaLoanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ChamaLoanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChamaLoans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChamaLoans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ChamaLoans
  **/
  _count?: true | ChamaLoanCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ChamaLoanAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ChamaLoanSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ChamaLoanMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ChamaLoanMaxAggregateInputType
}

export type GetChamaLoanAggregateType<T extends ChamaLoanAggregateArgs> = {
      [P in keyof T & keyof AggregateChamaLoan]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateChamaLoan[P]>
    : Prisma.GetScalarType<T[P], AggregateChamaLoan[P]>
}




export type ChamaLoanGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChamaLoanWhereInput
  orderBy?: Prisma.ChamaLoanOrderByWithAggregationInput | Prisma.ChamaLoanOrderByWithAggregationInput[]
  by: Prisma.ChamaLoanScalarFieldEnum[] | Prisma.ChamaLoanScalarFieldEnum
  having?: Prisma.ChamaLoanScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ChamaLoanCountAggregateInputType | true
  _avg?: ChamaLoanAvgAggregateInputType
  _sum?: ChamaLoanSumAggregateInputType
  _min?: ChamaLoanMinAggregateInputType
  _max?: ChamaLoanMaxAggregateInputType
}

export type ChamaLoanGroupByOutputType = {
  id: string
  chamaId: string
  lender: string
  loanAmount: number
  interest: number
  termMonths: number
  dueDate: Date
  paymentDate: Date | null
  createdAt: Date
  updatedAt: Date
  _count: ChamaLoanCountAggregateOutputType | null
  _avg: ChamaLoanAvgAggregateOutputType | null
  _sum: ChamaLoanSumAggregateOutputType | null
  _min: ChamaLoanMinAggregateOutputType | null
  _max: ChamaLoanMaxAggregateOutputType | null
}

type GetChamaLoanGroupByPayload<T extends ChamaLoanGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ChamaLoanGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ChamaLoanGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ChamaLoanGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ChamaLoanGroupByOutputType[P]>
      }
    >
  >



export type ChamaLoanWhereInput = {
  AND?: Prisma.ChamaLoanWhereInput | Prisma.ChamaLoanWhereInput[]
  OR?: Prisma.ChamaLoanWhereInput[]
  NOT?: Prisma.ChamaLoanWhereInput | Prisma.ChamaLoanWhereInput[]
  id?: Prisma.StringFilter<"ChamaLoan"> | string
  chamaId?: Prisma.StringFilter<"ChamaLoan"> | string
  lender?: Prisma.StringFilter<"ChamaLoan"> | string
  loanAmount?: Prisma.FloatFilter<"ChamaLoan"> | number
  interest?: Prisma.FloatFilter<"ChamaLoan"> | number
  termMonths?: Prisma.IntFilter<"ChamaLoan"> | number
  dueDate?: Prisma.DateTimeFilter<"ChamaLoan"> | Date | string
  paymentDate?: Prisma.DateTimeNullableFilter<"ChamaLoan"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ChamaLoan"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ChamaLoan"> | Date | string
  chama?: Prisma.XOR<Prisma.ChamaScalarRelationFilter, Prisma.ChamaWhereInput>
}

export type ChamaLoanOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  chamaId?: Prisma.SortOrder
  lender?: Prisma.SortOrder
  loanAmount?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  termMonths?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  chama?: Prisma.ChamaOrderByWithRelationInput
}

export type ChamaLoanWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ChamaLoanWhereInput | Prisma.ChamaLoanWhereInput[]
  OR?: Prisma.ChamaLoanWhereInput[]
  NOT?: Prisma.ChamaLoanWhereInput | Prisma.ChamaLoanWhereInput[]
  chamaId?: Prisma.StringFilter<"ChamaLoan"> | string
  lender?: Prisma.StringFilter<"ChamaLoan"> | string
  loanAmount?: Prisma.FloatFilter<"ChamaLoan"> | number
  interest?: Prisma.FloatFilter<"ChamaLoan"> | number
  termMonths?: Prisma.IntFilter<"ChamaLoan"> | number
  dueDate?: Prisma.DateTimeFilter<"ChamaLoan"> | Date | string
  paymentDate?: Prisma.DateTimeNullableFilter<"ChamaLoan"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ChamaLoan"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ChamaLoan"> | Date | string
  chama?: Prisma.XOR<Prisma.ChamaScalarRelationFilter, Prisma.ChamaWhereInput>
}, "id">

export type ChamaLoanOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  chamaId?: Prisma.SortOrder
  lender?: Prisma.SortOrder
  loanAmount?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  termMonths?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ChamaLoanCountOrderByAggregateInput
  _avg?: Prisma.ChamaLoanAvgOrderByAggregateInput
  _max?: Prisma.ChamaLoanMaxOrderByAggregateInput
  _min?: Prisma.ChamaLoanMinOrderByAggregateInput
  _sum?: Prisma.ChamaLoanSumOrderByAggregateInput
}

export type ChamaLoanScalarWhereWithAggregatesInput = {
  AND?: Prisma.ChamaLoanScalarWhereWithAggregatesInput | Prisma.ChamaLoanScalarWhereWithAggregatesInput[]
  OR?: Prisma.ChamaLoanScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ChamaLoanScalarWhereWithAggregatesInput | Prisma.ChamaLoanScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ChamaLoan"> | string
  chamaId?: Prisma.StringWithAggregatesFilter<"ChamaLoan"> | string
  lender?: Prisma.StringWithAggregatesFilter<"ChamaLoan"> | string
  loanAmount?: Prisma.FloatWithAggregatesFilter<"ChamaLoan"> | number
  interest?: Prisma.FloatWithAggregatesFilter<"ChamaLoan"> | number
  termMonths?: Prisma.IntWithAggregatesFilter<"ChamaLoan"> | number
  dueDate?: Prisma.DateTimeWithAggregatesFilter<"ChamaLoan"> | Date | string
  paymentDate?: Prisma.DateTimeNullableWithAggregatesFilter<"ChamaLoan"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ChamaLoan"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ChamaLoan"> | Date | string
}

export type ChamaLoanCreateInput = {
  id?: string
  lender: string
  loanAmount?: number
  interest?: number
  termMonths?: number
  dueDate: Date | string
  paymentDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  chama: Prisma.ChamaCreateNestedOneWithoutLoansInput
}

export type ChamaLoanUncheckedCreateInput = {
  id?: string
  chamaId: string
  lender: string
  loanAmount?: number
  interest?: number
  termMonths?: number
  dueDate: Date | string
  paymentDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChamaLoanUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lender?: Prisma.StringFieldUpdateOperationsInput | string
  loanAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  interest?: Prisma.FloatFieldUpdateOperationsInput | number
  termMonths?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chama?: Prisma.ChamaUpdateOneRequiredWithoutLoansNestedInput
}

export type ChamaLoanUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  chamaId?: Prisma.StringFieldUpdateOperationsInput | string
  lender?: Prisma.StringFieldUpdateOperationsInput | string
  loanAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  interest?: Prisma.FloatFieldUpdateOperationsInput | number
  termMonths?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChamaLoanCreateManyInput = {
  id?: string
  chamaId: string
  lender: string
  loanAmount?: number
  interest?: number
  termMonths?: number
  dueDate: Date | string
  paymentDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChamaLoanUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lender?: Prisma.StringFieldUpdateOperationsInput | string
  loanAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  interest?: Prisma.FloatFieldUpdateOperationsInput | number
  termMonths?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChamaLoanUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  chamaId?: Prisma.StringFieldUpdateOperationsInput | string
  lender?: Prisma.StringFieldUpdateOperationsInput | string
  loanAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  interest?: Prisma.FloatFieldUpdateOperationsInput | number
  termMonths?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChamaLoanListRelationFilter = {
  every?: Prisma.ChamaLoanWhereInput
  some?: Prisma.ChamaLoanWhereInput
  none?: Prisma.ChamaLoanWhereInput
}

export type ChamaLoanOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ChamaLoanCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chamaId?: Prisma.SortOrder
  lender?: Prisma.SortOrder
  loanAmount?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  termMonths?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChamaLoanAvgOrderByAggregateInput = {
  loanAmount?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  termMonths?: Prisma.SortOrder
}

export type ChamaLoanMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chamaId?: Prisma.SortOrder
  lender?: Prisma.SortOrder
  loanAmount?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  termMonths?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChamaLoanMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chamaId?: Prisma.SortOrder
  lender?: Prisma.SortOrder
  loanAmount?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  termMonths?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChamaLoanSumOrderByAggregateInput = {
  loanAmount?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  termMonths?: Prisma.SortOrder
}

export type ChamaLoanCreateNestedManyWithoutChamaInput = {
  create?: Prisma.XOR<Prisma.ChamaLoanCreateWithoutChamaInput, Prisma.ChamaLoanUncheckedCreateWithoutChamaInput> | Prisma.ChamaLoanCreateWithoutChamaInput[] | Prisma.ChamaLoanUncheckedCreateWithoutChamaInput[]
  connectOrCreate?: Prisma.ChamaLoanCreateOrConnectWithoutChamaInput | Prisma.ChamaLoanCreateOrConnectWithoutChamaInput[]
  createMany?: Prisma.ChamaLoanCreateManyChamaInputEnvelope
  connect?: Prisma.ChamaLoanWhereUniqueInput | Prisma.ChamaLoanWhereUniqueInput[]
}

export type ChamaLoanUncheckedCreateNestedManyWithoutChamaInput = {
  create?: Prisma.XOR<Prisma.ChamaLoanCreateWithoutChamaInput, Prisma.ChamaLoanUncheckedCreateWithoutChamaInput> | Prisma.ChamaLoanCreateWithoutChamaInput[] | Prisma.ChamaLoanUncheckedCreateWithoutChamaInput[]
  connectOrCreate?: Prisma.ChamaLoanCreateOrConnectWithoutChamaInput | Prisma.ChamaLoanCreateOrConnectWithoutChamaInput[]
  createMany?: Prisma.ChamaLoanCreateManyChamaInputEnvelope
  connect?: Prisma.ChamaLoanWhereUniqueInput | Prisma.ChamaLoanWhereUniqueInput[]
}

export type ChamaLoanUpdateManyWithoutChamaNestedInput = {
  create?: Prisma.XOR<Prisma.ChamaLoanCreateWithoutChamaInput, Prisma.ChamaLoanUncheckedCreateWithoutChamaInput> | Prisma.ChamaLoanCreateWithoutChamaInput[] | Prisma.ChamaLoanUncheckedCreateWithoutChamaInput[]
  connectOrCreate?: Prisma.ChamaLoanCreateOrConnectWithoutChamaInput | Prisma.ChamaLoanCreateOrConnectWithoutChamaInput[]
  upsert?: Prisma.ChamaLoanUpsertWithWhereUniqueWithoutChamaInput | Prisma.ChamaLoanUpsertWithWhereUniqueWithoutChamaInput[]
  createMany?: Prisma.ChamaLoanCreateManyChamaInputEnvelope
  set?: Prisma.ChamaLoanWhereUniqueInput | Prisma.ChamaLoanWhereUniqueInput[]
  disconnect?: Prisma.ChamaLoanWhereUniqueInput | Prisma.ChamaLoanWhereUniqueInput[]
  delete?: Prisma.ChamaLoanWhereUniqueInput | Prisma.ChamaLoanWhereUniqueInput[]
  connect?: Prisma.ChamaLoanWhereUniqueInput | Prisma.ChamaLoanWhereUniqueInput[]
  update?: Prisma.ChamaLoanUpdateWithWhereUniqueWithoutChamaInput | Prisma.ChamaLoanUpdateWithWhereUniqueWithoutChamaInput[]
  updateMany?: Prisma.ChamaLoanUpdateManyWithWhereWithoutChamaInput | Prisma.ChamaLoanUpdateManyWithWhereWithoutChamaInput[]
  deleteMany?: Prisma.ChamaLoanScalarWhereInput | Prisma.ChamaLoanScalarWhereInput[]
}

export type ChamaLoanUncheckedUpdateManyWithoutChamaNestedInput = {
  create?: Prisma.XOR<Prisma.ChamaLoanCreateWithoutChamaInput, Prisma.ChamaLoanUncheckedCreateWithoutChamaInput> | Prisma.ChamaLoanCreateWithoutChamaInput[] | Prisma.ChamaLoanUncheckedCreateWithoutChamaInput[]
  connectOrCreate?: Prisma.ChamaLoanCreateOrConnectWithoutChamaInput | Prisma.ChamaLoanCreateOrConnectWithoutChamaInput[]
  upsert?: Prisma.ChamaLoanUpsertWithWhereUniqueWithoutChamaInput | Prisma.ChamaLoanUpsertWithWhereUniqueWithoutChamaInput[]
  createMany?: Prisma.ChamaLoanCreateManyChamaInputEnvelope
  set?: Prisma.ChamaLoanWhereUniqueInput | Prisma.ChamaLoanWhereUniqueInput[]
  disconnect?: Prisma.ChamaLoanWhereUniqueInput | Prisma.ChamaLoanWhereUniqueInput[]
  delete?: Prisma.ChamaLoanWhereUniqueInput | Prisma.ChamaLoanWhereUniqueInput[]
  connect?: Prisma.ChamaLoanWhereUniqueInput | Prisma.ChamaLoanWhereUniqueInput[]
  update?: Prisma.ChamaLoanUpdateWithWhereUniqueWithoutChamaInput | Prisma.ChamaLoanUpdateWithWhereUniqueWithoutChamaInput[]
  updateMany?: Prisma.ChamaLoanUpdateManyWithWhereWithoutChamaInput | Prisma.ChamaLoanUpdateManyWithWhereWithoutChamaInput[]
  deleteMany?: Prisma.ChamaLoanScalarWhereInput | Prisma.ChamaLoanScalarWhereInput[]
}

export type ChamaLoanCreateWithoutChamaInput = {
  id?: string
  lender: string
  loanAmount?: number
  interest?: number
  termMonths?: number
  dueDate: Date | string
  paymentDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChamaLoanUncheckedCreateWithoutChamaInput = {
  id?: string
  lender: string
  loanAmount?: number
  interest?: number
  termMonths?: number
  dueDate: Date | string
  paymentDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChamaLoanCreateOrConnectWithoutChamaInput = {
  where: Prisma.ChamaLoanWhereUniqueInput
  create: Prisma.XOR<Prisma.ChamaLoanCreateWithoutChamaInput, Prisma.ChamaLoanUncheckedCreateWithoutChamaInput>
}

export type ChamaLoanCreateManyChamaInputEnvelope = {
  data: Prisma.ChamaLoanCreateManyChamaInput | Prisma.ChamaLoanCreateManyChamaInput[]
  skipDuplicates?: boolean
}

export type ChamaLoanUpsertWithWhereUniqueWithoutChamaInput = {
  where: Prisma.ChamaLoanWhereUniqueInput
  update: Prisma.XOR<Prisma.ChamaLoanUpdateWithoutChamaInput, Prisma.ChamaLoanUncheckedUpdateWithoutChamaInput>
  create: Prisma.XOR<Prisma.ChamaLoanCreateWithoutChamaInput, Prisma.ChamaLoanUncheckedCreateWithoutChamaInput>
}

export type ChamaLoanUpdateWithWhereUniqueWithoutChamaInput = {
  where: Prisma.ChamaLoanWhereUniqueInput
  data: Prisma.XOR<Prisma.ChamaLoanUpdateWithoutChamaInput, Prisma.ChamaLoanUncheckedUpdateWithoutChamaInput>
}

export type ChamaLoanUpdateManyWithWhereWithoutChamaInput = {
  where: Prisma.ChamaLoanScalarWhereInput
  data: Prisma.XOR<Prisma.ChamaLoanUpdateManyMutationInput, Prisma.ChamaLoanUncheckedUpdateManyWithoutChamaInput>
}

export type ChamaLoanScalarWhereInput = {
  AND?: Prisma.ChamaLoanScalarWhereInput | Prisma.ChamaLoanScalarWhereInput[]
  OR?: Prisma.ChamaLoanScalarWhereInput[]
  NOT?: Prisma.ChamaLoanScalarWhereInput | Prisma.ChamaLoanScalarWhereInput[]
  id?: Prisma.StringFilter<"ChamaLoan"> | string
  chamaId?: Prisma.StringFilter<"ChamaLoan"> | string
  lender?: Prisma.StringFilter<"ChamaLoan"> | string
  loanAmount?: Prisma.FloatFilter<"ChamaLoan"> | number
  interest?: Prisma.FloatFilter<"ChamaLoan"> | number
  termMonths?: Prisma.IntFilter<"ChamaLoan"> | number
  dueDate?: Prisma.DateTimeFilter<"ChamaLoan"> | Date | string
  paymentDate?: Prisma.DateTimeNullableFilter<"ChamaLoan"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ChamaLoan"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ChamaLoan"> | Date | string
}

export type ChamaLoanCreateManyChamaInput = {
  id?: string
  lender: string
  loanAmount?: number
  interest?: number
  termMonths?: number
  dueDate: Date | string
  paymentDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChamaLoanUpdateWithoutChamaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lender?: Prisma.StringFieldUpdateOperationsInput | string
  loanAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  interest?: Prisma.FloatFieldUpdateOperationsInput | number
  termMonths?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChamaLoanUncheckedUpdateWithoutChamaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lender?: Prisma.StringFieldUpdateOperationsInput | string
  loanAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  interest?: Prisma.FloatFieldUpdateOperationsInput | number
  termMonths?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChamaLoanUncheckedUpdateManyWithoutChamaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lender?: Prisma.StringFieldUpdateOperationsInput | string
  loanAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  interest?: Prisma.FloatFieldUpdateOperationsInput | number
  termMonths?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ChamaLoanSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  chamaId?: boolean
  lender?: boolean
  loanAmount?: boolean
  interest?: boolean
  termMonths?: boolean
  dueDate?: boolean
  paymentDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chama?: boolean | Prisma.ChamaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["chamaLoan"]>

export type ChamaLoanSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  chamaId?: boolean
  lender?: boolean
  loanAmount?: boolean
  interest?: boolean
  termMonths?: boolean
  dueDate?: boolean
  paymentDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chama?: boolean | Prisma.ChamaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["chamaLoan"]>

export type ChamaLoanSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  chamaId?: boolean
  lender?: boolean
  loanAmount?: boolean
  interest?: boolean
  termMonths?: boolean
  dueDate?: boolean
  paymentDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chama?: boolean | Prisma.ChamaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["chamaLoan"]>

export type ChamaLoanSelectScalar = {
  id?: boolean
  chamaId?: boolean
  lender?: boolean
  loanAmount?: boolean
  interest?: boolean
  termMonths?: boolean
  dueDate?: boolean
  paymentDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ChamaLoanOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "chamaId" | "lender" | "loanAmount" | "interest" | "termMonths" | "dueDate" | "paymentDate" | "createdAt" | "updatedAt", ExtArgs["result"]["chamaLoan"]>
export type ChamaLoanInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chama?: boolean | Prisma.ChamaDefaultArgs<ExtArgs>
}
export type ChamaLoanIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chama?: boolean | Prisma.ChamaDefaultArgs<ExtArgs>
}
export type ChamaLoanIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chama?: boolean | Prisma.ChamaDefaultArgs<ExtArgs>
}

export type $ChamaLoanPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ChamaLoan"
  objects: {
    chama: Prisma.$ChamaPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    chamaId: string
    lender: string
    loanAmount: number
    interest: number
    termMonths: number
    dueDate: Date
    paymentDate: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["chamaLoan"]>
  composites: {}
}

export type ChamaLoanGetPayload<S extends boolean | null | undefined | ChamaLoanDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload, S>

export type ChamaLoanCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ChamaLoanFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ChamaLoanCountAggregateInputType | true
  }

export interface ChamaLoanDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ChamaLoan'], meta: { name: 'ChamaLoan' } }
  /**
   * Find zero or one ChamaLoan that matches the filter.
   * @param {ChamaLoanFindUniqueArgs} args - Arguments to find a ChamaLoan
   * @example
   * // Get one ChamaLoan
   * const chamaLoan = await prisma.chamaLoan.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ChamaLoanFindUniqueArgs>(args: Prisma.SelectSubset<T, ChamaLoanFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ChamaLoanClient<runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ChamaLoan that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ChamaLoanFindUniqueOrThrowArgs} args - Arguments to find a ChamaLoan
   * @example
   * // Get one ChamaLoan
   * const chamaLoan = await prisma.chamaLoan.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ChamaLoanFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ChamaLoanFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChamaLoanClient<runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ChamaLoan that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChamaLoanFindFirstArgs} args - Arguments to find a ChamaLoan
   * @example
   * // Get one ChamaLoan
   * const chamaLoan = await prisma.chamaLoan.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ChamaLoanFindFirstArgs>(args?: Prisma.SelectSubset<T, ChamaLoanFindFirstArgs<ExtArgs>>): Prisma.Prisma__ChamaLoanClient<runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ChamaLoan that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChamaLoanFindFirstOrThrowArgs} args - Arguments to find a ChamaLoan
   * @example
   * // Get one ChamaLoan
   * const chamaLoan = await prisma.chamaLoan.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ChamaLoanFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ChamaLoanFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChamaLoanClient<runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ChamaLoans that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChamaLoanFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ChamaLoans
   * const chamaLoans = await prisma.chamaLoan.findMany()
   * 
   * // Get first 10 ChamaLoans
   * const chamaLoans = await prisma.chamaLoan.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const chamaLoanWithIdOnly = await prisma.chamaLoan.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ChamaLoanFindManyArgs>(args?: Prisma.SelectSubset<T, ChamaLoanFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ChamaLoan.
   * @param {ChamaLoanCreateArgs} args - Arguments to create a ChamaLoan.
   * @example
   * // Create one ChamaLoan
   * const ChamaLoan = await prisma.chamaLoan.create({
   *   data: {
   *     // ... data to create a ChamaLoan
   *   }
   * })
   * 
   */
  create<T extends ChamaLoanCreateArgs>(args: Prisma.SelectSubset<T, ChamaLoanCreateArgs<ExtArgs>>): Prisma.Prisma__ChamaLoanClient<runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ChamaLoans.
   * @param {ChamaLoanCreateManyArgs} args - Arguments to create many ChamaLoans.
   * @example
   * // Create many ChamaLoans
   * const chamaLoan = await prisma.chamaLoan.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ChamaLoanCreateManyArgs>(args?: Prisma.SelectSubset<T, ChamaLoanCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ChamaLoans and returns the data saved in the database.
   * @param {ChamaLoanCreateManyAndReturnArgs} args - Arguments to create many ChamaLoans.
   * @example
   * // Create many ChamaLoans
   * const chamaLoan = await prisma.chamaLoan.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ChamaLoans and only return the `id`
   * const chamaLoanWithIdOnly = await prisma.chamaLoan.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ChamaLoanCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ChamaLoanCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ChamaLoan.
   * @param {ChamaLoanDeleteArgs} args - Arguments to delete one ChamaLoan.
   * @example
   * // Delete one ChamaLoan
   * const ChamaLoan = await prisma.chamaLoan.delete({
   *   where: {
   *     // ... filter to delete one ChamaLoan
   *   }
   * })
   * 
   */
  delete<T extends ChamaLoanDeleteArgs>(args: Prisma.SelectSubset<T, ChamaLoanDeleteArgs<ExtArgs>>): Prisma.Prisma__ChamaLoanClient<runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ChamaLoan.
   * @param {ChamaLoanUpdateArgs} args - Arguments to update one ChamaLoan.
   * @example
   * // Update one ChamaLoan
   * const chamaLoan = await prisma.chamaLoan.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ChamaLoanUpdateArgs>(args: Prisma.SelectSubset<T, ChamaLoanUpdateArgs<ExtArgs>>): Prisma.Prisma__ChamaLoanClient<runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ChamaLoans.
   * @param {ChamaLoanDeleteManyArgs} args - Arguments to filter ChamaLoans to delete.
   * @example
   * // Delete a few ChamaLoans
   * const { count } = await prisma.chamaLoan.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ChamaLoanDeleteManyArgs>(args?: Prisma.SelectSubset<T, ChamaLoanDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ChamaLoans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChamaLoanUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ChamaLoans
   * const chamaLoan = await prisma.chamaLoan.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ChamaLoanUpdateManyArgs>(args: Prisma.SelectSubset<T, ChamaLoanUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ChamaLoans and returns the data updated in the database.
   * @param {ChamaLoanUpdateManyAndReturnArgs} args - Arguments to update many ChamaLoans.
   * @example
   * // Update many ChamaLoans
   * const chamaLoan = await prisma.chamaLoan.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ChamaLoans and only return the `id`
   * const chamaLoanWithIdOnly = await prisma.chamaLoan.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ChamaLoanUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ChamaLoanUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ChamaLoan.
   * @param {ChamaLoanUpsertArgs} args - Arguments to update or create a ChamaLoan.
   * @example
   * // Update or create a ChamaLoan
   * const chamaLoan = await prisma.chamaLoan.upsert({
   *   create: {
   *     // ... data to create a ChamaLoan
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ChamaLoan we want to update
   *   }
   * })
   */
  upsert<T extends ChamaLoanUpsertArgs>(args: Prisma.SelectSubset<T, ChamaLoanUpsertArgs<ExtArgs>>): Prisma.Prisma__ChamaLoanClient<runtime.Types.Result.GetResult<Prisma.$ChamaLoanPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ChamaLoans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChamaLoanCountArgs} args - Arguments to filter ChamaLoans to count.
   * @example
   * // Count the number of ChamaLoans
   * const count = await prisma.chamaLoan.count({
   *   where: {
   *     // ... the filter for the ChamaLoans we want to count
   *   }
   * })
  **/
  count<T extends ChamaLoanCountArgs>(
    args?: Prisma.Subset<T, ChamaLoanCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ChamaLoanCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ChamaLoan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChamaLoanAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ChamaLoanAggregateArgs>(args: Prisma.Subset<T, ChamaLoanAggregateArgs>): Prisma.PrismaPromise<GetChamaLoanAggregateType<T>>

  /**
   * Group by ChamaLoan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChamaLoanGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ChamaLoanGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ChamaLoanGroupByArgs['orderBy'] }
      : { orderBy?: ChamaLoanGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ChamaLoanGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetChamaLoanGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ChamaLoan model
 */
readonly fields: ChamaLoanFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ChamaLoan.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ChamaLoanClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  chama<T extends Prisma.ChamaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChamaDefaultArgs<ExtArgs>>): Prisma.Prisma__ChamaClient<runtime.Types.Result.GetResult<Prisma.$ChamaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ChamaLoan model
 */
export interface ChamaLoanFieldRefs {
  readonly id: Prisma.FieldRef<"ChamaLoan", 'String'>
  readonly chamaId: Prisma.FieldRef<"ChamaLoan", 'String'>
  readonly lender: Prisma.FieldRef<"ChamaLoan", 'String'>
  readonly loanAmount: Prisma.FieldRef<"ChamaLoan", 'Float'>
  readonly interest: Prisma.FieldRef<"ChamaLoan", 'Float'>
  readonly termMonths: Prisma.FieldRef<"ChamaLoan", 'Int'>
  readonly dueDate: Prisma.FieldRef<"ChamaLoan", 'DateTime'>
  readonly paymentDate: Prisma.FieldRef<"ChamaLoan", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ChamaLoan", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ChamaLoan", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ChamaLoan findUnique
 */
export type ChamaLoanFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanInclude<ExtArgs> | null
  /**
   * Filter, which ChamaLoan to fetch.
   */
  where: Prisma.ChamaLoanWhereUniqueInput
}

/**
 * ChamaLoan findUniqueOrThrow
 */
export type ChamaLoanFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanInclude<ExtArgs> | null
  /**
   * Filter, which ChamaLoan to fetch.
   */
  where: Prisma.ChamaLoanWhereUniqueInput
}

/**
 * ChamaLoan findFirst
 */
export type ChamaLoanFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanInclude<ExtArgs> | null
  /**
   * Filter, which ChamaLoan to fetch.
   */
  where?: Prisma.ChamaLoanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChamaLoans to fetch.
   */
  orderBy?: Prisma.ChamaLoanOrderByWithRelationInput | Prisma.ChamaLoanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ChamaLoans.
   */
  cursor?: Prisma.ChamaLoanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChamaLoans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChamaLoans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChamaLoans.
   */
  distinct?: Prisma.ChamaLoanScalarFieldEnum | Prisma.ChamaLoanScalarFieldEnum[]
}

/**
 * ChamaLoan findFirstOrThrow
 */
export type ChamaLoanFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanInclude<ExtArgs> | null
  /**
   * Filter, which ChamaLoan to fetch.
   */
  where?: Prisma.ChamaLoanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChamaLoans to fetch.
   */
  orderBy?: Prisma.ChamaLoanOrderByWithRelationInput | Prisma.ChamaLoanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ChamaLoans.
   */
  cursor?: Prisma.ChamaLoanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChamaLoans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChamaLoans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChamaLoans.
   */
  distinct?: Prisma.ChamaLoanScalarFieldEnum | Prisma.ChamaLoanScalarFieldEnum[]
}

/**
 * ChamaLoan findMany
 */
export type ChamaLoanFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanInclude<ExtArgs> | null
  /**
   * Filter, which ChamaLoans to fetch.
   */
  where?: Prisma.ChamaLoanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChamaLoans to fetch.
   */
  orderBy?: Prisma.ChamaLoanOrderByWithRelationInput | Prisma.ChamaLoanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ChamaLoans.
   */
  cursor?: Prisma.ChamaLoanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChamaLoans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChamaLoans.
   */
  skip?: number
  distinct?: Prisma.ChamaLoanScalarFieldEnum | Prisma.ChamaLoanScalarFieldEnum[]
}

/**
 * ChamaLoan create
 */
export type ChamaLoanCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanInclude<ExtArgs> | null
  /**
   * The data needed to create a ChamaLoan.
   */
  data: Prisma.XOR<Prisma.ChamaLoanCreateInput, Prisma.ChamaLoanUncheckedCreateInput>
}

/**
 * ChamaLoan createMany
 */
export type ChamaLoanCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ChamaLoans.
   */
  data: Prisma.ChamaLoanCreateManyInput | Prisma.ChamaLoanCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ChamaLoan createManyAndReturn
 */
export type ChamaLoanCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * The data used to create many ChamaLoans.
   */
  data: Prisma.ChamaLoanCreateManyInput | Prisma.ChamaLoanCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ChamaLoan update
 */
export type ChamaLoanUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanInclude<ExtArgs> | null
  /**
   * The data needed to update a ChamaLoan.
   */
  data: Prisma.XOR<Prisma.ChamaLoanUpdateInput, Prisma.ChamaLoanUncheckedUpdateInput>
  /**
   * Choose, which ChamaLoan to update.
   */
  where: Prisma.ChamaLoanWhereUniqueInput
}

/**
 * ChamaLoan updateMany
 */
export type ChamaLoanUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ChamaLoans.
   */
  data: Prisma.XOR<Prisma.ChamaLoanUpdateManyMutationInput, Prisma.ChamaLoanUncheckedUpdateManyInput>
  /**
   * Filter which ChamaLoans to update
   */
  where?: Prisma.ChamaLoanWhereInput
  /**
   * Limit how many ChamaLoans to update.
   */
  limit?: number
}

/**
 * ChamaLoan updateManyAndReturn
 */
export type ChamaLoanUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * The data used to update ChamaLoans.
   */
  data: Prisma.XOR<Prisma.ChamaLoanUpdateManyMutationInput, Prisma.ChamaLoanUncheckedUpdateManyInput>
  /**
   * Filter which ChamaLoans to update
   */
  where?: Prisma.ChamaLoanWhereInput
  /**
   * Limit how many ChamaLoans to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ChamaLoan upsert
 */
export type ChamaLoanUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanInclude<ExtArgs> | null
  /**
   * The filter to search for the ChamaLoan to update in case it exists.
   */
  where: Prisma.ChamaLoanWhereUniqueInput
  /**
   * In case the ChamaLoan found by the `where` argument doesn't exist, create a new ChamaLoan with this data.
   */
  create: Prisma.XOR<Prisma.ChamaLoanCreateInput, Prisma.ChamaLoanUncheckedCreateInput>
  /**
   * In case the ChamaLoan was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ChamaLoanUpdateInput, Prisma.ChamaLoanUncheckedUpdateInput>
}

/**
 * ChamaLoan delete
 */
export type ChamaLoanDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanInclude<ExtArgs> | null
  /**
   * Filter which ChamaLoan to delete.
   */
  where: Prisma.ChamaLoanWhereUniqueInput
}

/**
 * ChamaLoan deleteMany
 */
export type ChamaLoanDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ChamaLoans to delete
   */
  where?: Prisma.ChamaLoanWhereInput
  /**
   * Limit how many ChamaLoans to delete.
   */
  limit?: number
}

/**
 * ChamaLoan without action
 */
export type ChamaLoanDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChamaLoan
   */
  select?: Prisma.ChamaLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChamaLoan
   */
  omit?: Prisma.ChamaLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChamaLoanInclude<ExtArgs> | null
}
