
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Deduction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Deduction
 * 
 */
export type DeductionModel = runtime.Types.Result.DefaultSelection<Prisma.$DeductionPayload>

export type AggregateDeduction = {
  _count: DeductionCountAggregateOutputType | null
  _avg: DeductionAvgAggregateOutputType | null
  _sum: DeductionSumAggregateOutputType | null
  _min: DeductionMinAggregateOutputType | null
  _max: DeductionMaxAggregateOutputType | null
}

export type DeductionAvgAggregateOutputType = {
  amount: number | null
}

export type DeductionSumAggregateOutputType = {
  amount: number | null
}

export type DeductionMinAggregateOutputType = {
  id: string | null
  savingId: string | null
  loanId: string | null
  loanType: string | null
  penaltyId: string | null
  amount: number | null
  status: $Enums.TransactionStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DeductionMaxAggregateOutputType = {
  id: string | null
  savingId: string | null
  loanId: string | null
  loanType: string | null
  penaltyId: string | null
  amount: number | null
  status: $Enums.TransactionStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DeductionCountAggregateOutputType = {
  id: number
  savingId: number
  loanId: number
  loanType: number
  penaltyId: number
  amount: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DeductionAvgAggregateInputType = {
  amount?: true
}

export type DeductionSumAggregateInputType = {
  amount?: true
}

export type DeductionMinAggregateInputType = {
  id?: true
  savingId?: true
  loanId?: true
  loanType?: true
  penaltyId?: true
  amount?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type DeductionMaxAggregateInputType = {
  id?: true
  savingId?: true
  loanId?: true
  loanType?: true
  penaltyId?: true
  amount?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type DeductionCountAggregateInputType = {
  id?: true
  savingId?: true
  loanId?: true
  loanType?: true
  penaltyId?: true
  amount?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DeductionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Deduction to aggregate.
   */
  where?: Prisma.DeductionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Deductions to fetch.
   */
  orderBy?: Prisma.DeductionOrderByWithRelationInput | Prisma.DeductionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DeductionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Deductions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Deductions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Deductions
  **/
  _count?: true | DeductionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DeductionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DeductionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DeductionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DeductionMaxAggregateInputType
}

export type GetDeductionAggregateType<T extends DeductionAggregateArgs> = {
      [P in keyof T & keyof AggregateDeduction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDeduction[P]>
    : Prisma.GetScalarType<T[P], AggregateDeduction[P]>
}




export type DeductionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DeductionWhereInput
  orderBy?: Prisma.DeductionOrderByWithAggregationInput | Prisma.DeductionOrderByWithAggregationInput[]
  by: Prisma.DeductionScalarFieldEnum[] | Prisma.DeductionScalarFieldEnum
  having?: Prisma.DeductionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DeductionCountAggregateInputType | true
  _avg?: DeductionAvgAggregateInputType
  _sum?: DeductionSumAggregateInputType
  _min?: DeductionMinAggregateInputType
  _max?: DeductionMaxAggregateInputType
}

export type DeductionGroupByOutputType = {
  id: string
  savingId: string
  loanId: string | null
  loanType: string | null
  penaltyId: string | null
  amount: number
  status: $Enums.TransactionStatus
  createdAt: Date
  updatedAt: Date
  _count: DeductionCountAggregateOutputType | null
  _avg: DeductionAvgAggregateOutputType | null
  _sum: DeductionSumAggregateOutputType | null
  _min: DeductionMinAggregateOutputType | null
  _max: DeductionMaxAggregateOutputType | null
}

type GetDeductionGroupByPayload<T extends DeductionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DeductionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DeductionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DeductionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DeductionGroupByOutputType[P]>
      }
    >
  >



export type DeductionWhereInput = {
  AND?: Prisma.DeductionWhereInput | Prisma.DeductionWhereInput[]
  OR?: Prisma.DeductionWhereInput[]
  NOT?: Prisma.DeductionWhereInput | Prisma.DeductionWhereInput[]
  id?: Prisma.StringFilter<"Deduction"> | string
  savingId?: Prisma.StringFilter<"Deduction"> | string
  loanId?: Prisma.StringNullableFilter<"Deduction"> | string | null
  loanType?: Prisma.StringNullableFilter<"Deduction"> | string | null
  penaltyId?: Prisma.StringNullableFilter<"Deduction"> | string | null
  amount?: Prisma.FloatFilter<"Deduction"> | number
  status?: Prisma.EnumTransactionStatusFilter<"Deduction"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"Deduction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Deduction"> | Date | string
  saving?: Prisma.XOR<Prisma.SavingScalarRelationFilter, Prisma.SavingWhereInput>
  loan?: Prisma.XOR<Prisma.LoanNullableScalarRelationFilter, Prisma.LoanWhereInput> | null
  penalty?: Prisma.XOR<Prisma.PenaltyNullableScalarRelationFilter, Prisma.PenaltyWhereInput> | null
}

export type DeductionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  savingId?: Prisma.SortOrder
  loanId?: Prisma.SortOrderInput | Prisma.SortOrder
  loanType?: Prisma.SortOrderInput | Prisma.SortOrder
  penaltyId?: Prisma.SortOrderInput | Prisma.SortOrder
  amount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  saving?: Prisma.SavingOrderByWithRelationInput
  loan?: Prisma.LoanOrderByWithRelationInput
  penalty?: Prisma.PenaltyOrderByWithRelationInput
}

export type DeductionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DeductionWhereInput | Prisma.DeductionWhereInput[]
  OR?: Prisma.DeductionWhereInput[]
  NOT?: Prisma.DeductionWhereInput | Prisma.DeductionWhereInput[]
  savingId?: Prisma.StringFilter<"Deduction"> | string
  loanId?: Prisma.StringNullableFilter<"Deduction"> | string | null
  loanType?: Prisma.StringNullableFilter<"Deduction"> | string | null
  penaltyId?: Prisma.StringNullableFilter<"Deduction"> | string | null
  amount?: Prisma.FloatFilter<"Deduction"> | number
  status?: Prisma.EnumTransactionStatusFilter<"Deduction"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"Deduction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Deduction"> | Date | string
  saving?: Prisma.XOR<Prisma.SavingScalarRelationFilter, Prisma.SavingWhereInput>
  loan?: Prisma.XOR<Prisma.LoanNullableScalarRelationFilter, Prisma.LoanWhereInput> | null
  penalty?: Prisma.XOR<Prisma.PenaltyNullableScalarRelationFilter, Prisma.PenaltyWhereInput> | null
}, "id">

export type DeductionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  savingId?: Prisma.SortOrder
  loanId?: Prisma.SortOrderInput | Prisma.SortOrder
  loanType?: Prisma.SortOrderInput | Prisma.SortOrder
  penaltyId?: Prisma.SortOrderInput | Prisma.SortOrder
  amount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DeductionCountOrderByAggregateInput
  _avg?: Prisma.DeductionAvgOrderByAggregateInput
  _max?: Prisma.DeductionMaxOrderByAggregateInput
  _min?: Prisma.DeductionMinOrderByAggregateInput
  _sum?: Prisma.DeductionSumOrderByAggregateInput
}

export type DeductionScalarWhereWithAggregatesInput = {
  AND?: Prisma.DeductionScalarWhereWithAggregatesInput | Prisma.DeductionScalarWhereWithAggregatesInput[]
  OR?: Prisma.DeductionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DeductionScalarWhereWithAggregatesInput | Prisma.DeductionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Deduction"> | string
  savingId?: Prisma.StringWithAggregatesFilter<"Deduction"> | string
  loanId?: Prisma.StringNullableWithAggregatesFilter<"Deduction"> | string | null
  loanType?: Prisma.StringNullableWithAggregatesFilter<"Deduction"> | string | null
  penaltyId?: Prisma.StringNullableWithAggregatesFilter<"Deduction"> | string | null
  amount?: Prisma.FloatWithAggregatesFilter<"Deduction"> | number
  status?: Prisma.EnumTransactionStatusWithAggregatesFilter<"Deduction"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Deduction"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Deduction"> | Date | string
}

export type DeductionCreateInput = {
  id?: string
  loanType?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  saving: Prisma.SavingCreateNestedOneWithoutDeductionsInput
  loan?: Prisma.LoanCreateNestedOneWithoutDeductionsInput
  penalty?: Prisma.PenaltyCreateNestedOneWithoutDeductionsInput
}

export type DeductionUncheckedCreateInput = {
  id?: string
  savingId: string
  loanId?: string | null
  loanType?: string | null
  penaltyId?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DeductionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  saving?: Prisma.SavingUpdateOneRequiredWithoutDeductionsNestedInput
  loan?: Prisma.LoanUpdateOneWithoutDeductionsNestedInput
  penalty?: Prisma.PenaltyUpdateOneWithoutDeductionsNestedInput
}

export type DeductionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  savingId?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeductionCreateManyInput = {
  id?: string
  savingId: string
  loanId?: string | null
  loanType?: string | null
  penaltyId?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DeductionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeductionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  savingId?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeductionListRelationFilter = {
  every?: Prisma.DeductionWhereInput
  some?: Prisma.DeductionWhereInput
  none?: Prisma.DeductionWhereInput
}

export type DeductionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DeductionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  savingId?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  loanType?: Prisma.SortOrder
  penaltyId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DeductionAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type DeductionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  savingId?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  loanType?: Prisma.SortOrder
  penaltyId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DeductionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  savingId?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  loanType?: Prisma.SortOrder
  penaltyId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DeductionSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type DeductionCreateNestedManyWithoutSavingInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutSavingInput, Prisma.DeductionUncheckedCreateWithoutSavingInput> | Prisma.DeductionCreateWithoutSavingInput[] | Prisma.DeductionUncheckedCreateWithoutSavingInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutSavingInput | Prisma.DeductionCreateOrConnectWithoutSavingInput[]
  createMany?: Prisma.DeductionCreateManySavingInputEnvelope
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
}

export type DeductionUncheckedCreateNestedManyWithoutSavingInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutSavingInput, Prisma.DeductionUncheckedCreateWithoutSavingInput> | Prisma.DeductionCreateWithoutSavingInput[] | Prisma.DeductionUncheckedCreateWithoutSavingInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutSavingInput | Prisma.DeductionCreateOrConnectWithoutSavingInput[]
  createMany?: Prisma.DeductionCreateManySavingInputEnvelope
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
}

export type DeductionUpdateManyWithoutSavingNestedInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutSavingInput, Prisma.DeductionUncheckedCreateWithoutSavingInput> | Prisma.DeductionCreateWithoutSavingInput[] | Prisma.DeductionUncheckedCreateWithoutSavingInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutSavingInput | Prisma.DeductionCreateOrConnectWithoutSavingInput[]
  upsert?: Prisma.DeductionUpsertWithWhereUniqueWithoutSavingInput | Prisma.DeductionUpsertWithWhereUniqueWithoutSavingInput[]
  createMany?: Prisma.DeductionCreateManySavingInputEnvelope
  set?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  disconnect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  delete?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  update?: Prisma.DeductionUpdateWithWhereUniqueWithoutSavingInput | Prisma.DeductionUpdateWithWhereUniqueWithoutSavingInput[]
  updateMany?: Prisma.DeductionUpdateManyWithWhereWithoutSavingInput | Prisma.DeductionUpdateManyWithWhereWithoutSavingInput[]
  deleteMany?: Prisma.DeductionScalarWhereInput | Prisma.DeductionScalarWhereInput[]
}

export type DeductionUncheckedUpdateManyWithoutSavingNestedInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutSavingInput, Prisma.DeductionUncheckedCreateWithoutSavingInput> | Prisma.DeductionCreateWithoutSavingInput[] | Prisma.DeductionUncheckedCreateWithoutSavingInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutSavingInput | Prisma.DeductionCreateOrConnectWithoutSavingInput[]
  upsert?: Prisma.DeductionUpsertWithWhereUniqueWithoutSavingInput | Prisma.DeductionUpsertWithWhereUniqueWithoutSavingInput[]
  createMany?: Prisma.DeductionCreateManySavingInputEnvelope
  set?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  disconnect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  delete?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  update?: Prisma.DeductionUpdateWithWhereUniqueWithoutSavingInput | Prisma.DeductionUpdateWithWhereUniqueWithoutSavingInput[]
  updateMany?: Prisma.DeductionUpdateManyWithWhereWithoutSavingInput | Prisma.DeductionUpdateManyWithWhereWithoutSavingInput[]
  deleteMany?: Prisma.DeductionScalarWhereInput | Prisma.DeductionScalarWhereInput[]
}

export type DeductionCreateNestedManyWithoutLoanInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutLoanInput, Prisma.DeductionUncheckedCreateWithoutLoanInput> | Prisma.DeductionCreateWithoutLoanInput[] | Prisma.DeductionUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutLoanInput | Prisma.DeductionCreateOrConnectWithoutLoanInput[]
  createMany?: Prisma.DeductionCreateManyLoanInputEnvelope
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
}

export type DeductionUncheckedCreateNestedManyWithoutLoanInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutLoanInput, Prisma.DeductionUncheckedCreateWithoutLoanInput> | Prisma.DeductionCreateWithoutLoanInput[] | Prisma.DeductionUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutLoanInput | Prisma.DeductionCreateOrConnectWithoutLoanInput[]
  createMany?: Prisma.DeductionCreateManyLoanInputEnvelope
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
}

export type DeductionUpdateManyWithoutLoanNestedInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutLoanInput, Prisma.DeductionUncheckedCreateWithoutLoanInput> | Prisma.DeductionCreateWithoutLoanInput[] | Prisma.DeductionUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutLoanInput | Prisma.DeductionCreateOrConnectWithoutLoanInput[]
  upsert?: Prisma.DeductionUpsertWithWhereUniqueWithoutLoanInput | Prisma.DeductionUpsertWithWhereUniqueWithoutLoanInput[]
  createMany?: Prisma.DeductionCreateManyLoanInputEnvelope
  set?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  disconnect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  delete?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  update?: Prisma.DeductionUpdateWithWhereUniqueWithoutLoanInput | Prisma.DeductionUpdateWithWhereUniqueWithoutLoanInput[]
  updateMany?: Prisma.DeductionUpdateManyWithWhereWithoutLoanInput | Prisma.DeductionUpdateManyWithWhereWithoutLoanInput[]
  deleteMany?: Prisma.DeductionScalarWhereInput | Prisma.DeductionScalarWhereInput[]
}

export type DeductionUncheckedUpdateManyWithoutLoanNestedInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutLoanInput, Prisma.DeductionUncheckedCreateWithoutLoanInput> | Prisma.DeductionCreateWithoutLoanInput[] | Prisma.DeductionUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutLoanInput | Prisma.DeductionCreateOrConnectWithoutLoanInput[]
  upsert?: Prisma.DeductionUpsertWithWhereUniqueWithoutLoanInput | Prisma.DeductionUpsertWithWhereUniqueWithoutLoanInput[]
  createMany?: Prisma.DeductionCreateManyLoanInputEnvelope
  set?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  disconnect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  delete?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  update?: Prisma.DeductionUpdateWithWhereUniqueWithoutLoanInput | Prisma.DeductionUpdateWithWhereUniqueWithoutLoanInput[]
  updateMany?: Prisma.DeductionUpdateManyWithWhereWithoutLoanInput | Prisma.DeductionUpdateManyWithWhereWithoutLoanInput[]
  deleteMany?: Prisma.DeductionScalarWhereInput | Prisma.DeductionScalarWhereInput[]
}

export type DeductionCreateNestedManyWithoutPenaltyInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutPenaltyInput, Prisma.DeductionUncheckedCreateWithoutPenaltyInput> | Prisma.DeductionCreateWithoutPenaltyInput[] | Prisma.DeductionUncheckedCreateWithoutPenaltyInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutPenaltyInput | Prisma.DeductionCreateOrConnectWithoutPenaltyInput[]
  createMany?: Prisma.DeductionCreateManyPenaltyInputEnvelope
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
}

export type DeductionUncheckedCreateNestedManyWithoutPenaltyInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutPenaltyInput, Prisma.DeductionUncheckedCreateWithoutPenaltyInput> | Prisma.DeductionCreateWithoutPenaltyInput[] | Prisma.DeductionUncheckedCreateWithoutPenaltyInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutPenaltyInput | Prisma.DeductionCreateOrConnectWithoutPenaltyInput[]
  createMany?: Prisma.DeductionCreateManyPenaltyInputEnvelope
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
}

export type DeductionUpdateManyWithoutPenaltyNestedInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutPenaltyInput, Prisma.DeductionUncheckedCreateWithoutPenaltyInput> | Prisma.DeductionCreateWithoutPenaltyInput[] | Prisma.DeductionUncheckedCreateWithoutPenaltyInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutPenaltyInput | Prisma.DeductionCreateOrConnectWithoutPenaltyInput[]
  upsert?: Prisma.DeductionUpsertWithWhereUniqueWithoutPenaltyInput | Prisma.DeductionUpsertWithWhereUniqueWithoutPenaltyInput[]
  createMany?: Prisma.DeductionCreateManyPenaltyInputEnvelope
  set?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  disconnect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  delete?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  update?: Prisma.DeductionUpdateWithWhereUniqueWithoutPenaltyInput | Prisma.DeductionUpdateWithWhereUniqueWithoutPenaltyInput[]
  updateMany?: Prisma.DeductionUpdateManyWithWhereWithoutPenaltyInput | Prisma.DeductionUpdateManyWithWhereWithoutPenaltyInput[]
  deleteMany?: Prisma.DeductionScalarWhereInput | Prisma.DeductionScalarWhereInput[]
}

export type DeductionUncheckedUpdateManyWithoutPenaltyNestedInput = {
  create?: Prisma.XOR<Prisma.DeductionCreateWithoutPenaltyInput, Prisma.DeductionUncheckedCreateWithoutPenaltyInput> | Prisma.DeductionCreateWithoutPenaltyInput[] | Prisma.DeductionUncheckedCreateWithoutPenaltyInput[]
  connectOrCreate?: Prisma.DeductionCreateOrConnectWithoutPenaltyInput | Prisma.DeductionCreateOrConnectWithoutPenaltyInput[]
  upsert?: Prisma.DeductionUpsertWithWhereUniqueWithoutPenaltyInput | Prisma.DeductionUpsertWithWhereUniqueWithoutPenaltyInput[]
  createMany?: Prisma.DeductionCreateManyPenaltyInputEnvelope
  set?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  disconnect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  delete?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  connect?: Prisma.DeductionWhereUniqueInput | Prisma.DeductionWhereUniqueInput[]
  update?: Prisma.DeductionUpdateWithWhereUniqueWithoutPenaltyInput | Prisma.DeductionUpdateWithWhereUniqueWithoutPenaltyInput[]
  updateMany?: Prisma.DeductionUpdateManyWithWhereWithoutPenaltyInput | Prisma.DeductionUpdateManyWithWhereWithoutPenaltyInput[]
  deleteMany?: Prisma.DeductionScalarWhereInput | Prisma.DeductionScalarWhereInput[]
}

export type DeductionCreateWithoutSavingInput = {
  id?: string
  loanType?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  loan?: Prisma.LoanCreateNestedOneWithoutDeductionsInput
  penalty?: Prisma.PenaltyCreateNestedOneWithoutDeductionsInput
}

export type DeductionUncheckedCreateWithoutSavingInput = {
  id?: string
  loanId?: string | null
  loanType?: string | null
  penaltyId?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DeductionCreateOrConnectWithoutSavingInput = {
  where: Prisma.DeductionWhereUniqueInput
  create: Prisma.XOR<Prisma.DeductionCreateWithoutSavingInput, Prisma.DeductionUncheckedCreateWithoutSavingInput>
}

export type DeductionCreateManySavingInputEnvelope = {
  data: Prisma.DeductionCreateManySavingInput | Prisma.DeductionCreateManySavingInput[]
  skipDuplicates?: boolean
}

export type DeductionUpsertWithWhereUniqueWithoutSavingInput = {
  where: Prisma.DeductionWhereUniqueInput
  update: Prisma.XOR<Prisma.DeductionUpdateWithoutSavingInput, Prisma.DeductionUncheckedUpdateWithoutSavingInput>
  create: Prisma.XOR<Prisma.DeductionCreateWithoutSavingInput, Prisma.DeductionUncheckedCreateWithoutSavingInput>
}

export type DeductionUpdateWithWhereUniqueWithoutSavingInput = {
  where: Prisma.DeductionWhereUniqueInput
  data: Prisma.XOR<Prisma.DeductionUpdateWithoutSavingInput, Prisma.DeductionUncheckedUpdateWithoutSavingInput>
}

export type DeductionUpdateManyWithWhereWithoutSavingInput = {
  where: Prisma.DeductionScalarWhereInput
  data: Prisma.XOR<Prisma.DeductionUpdateManyMutationInput, Prisma.DeductionUncheckedUpdateManyWithoutSavingInput>
}

export type DeductionScalarWhereInput = {
  AND?: Prisma.DeductionScalarWhereInput | Prisma.DeductionScalarWhereInput[]
  OR?: Prisma.DeductionScalarWhereInput[]
  NOT?: Prisma.DeductionScalarWhereInput | Prisma.DeductionScalarWhereInput[]
  id?: Prisma.StringFilter<"Deduction"> | string
  savingId?: Prisma.StringFilter<"Deduction"> | string
  loanId?: Prisma.StringNullableFilter<"Deduction"> | string | null
  loanType?: Prisma.StringNullableFilter<"Deduction"> | string | null
  penaltyId?: Prisma.StringNullableFilter<"Deduction"> | string | null
  amount?: Prisma.FloatFilter<"Deduction"> | number
  status?: Prisma.EnumTransactionStatusFilter<"Deduction"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"Deduction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Deduction"> | Date | string
}

export type DeductionCreateWithoutLoanInput = {
  id?: string
  loanType?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  saving: Prisma.SavingCreateNestedOneWithoutDeductionsInput
  penalty?: Prisma.PenaltyCreateNestedOneWithoutDeductionsInput
}

export type DeductionUncheckedCreateWithoutLoanInput = {
  id?: string
  savingId: string
  loanType?: string | null
  penaltyId?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DeductionCreateOrConnectWithoutLoanInput = {
  where: Prisma.DeductionWhereUniqueInput
  create: Prisma.XOR<Prisma.DeductionCreateWithoutLoanInput, Prisma.DeductionUncheckedCreateWithoutLoanInput>
}

export type DeductionCreateManyLoanInputEnvelope = {
  data: Prisma.DeductionCreateManyLoanInput | Prisma.DeductionCreateManyLoanInput[]
  skipDuplicates?: boolean
}

export type DeductionUpsertWithWhereUniqueWithoutLoanInput = {
  where: Prisma.DeductionWhereUniqueInput
  update: Prisma.XOR<Prisma.DeductionUpdateWithoutLoanInput, Prisma.DeductionUncheckedUpdateWithoutLoanInput>
  create: Prisma.XOR<Prisma.DeductionCreateWithoutLoanInput, Prisma.DeductionUncheckedCreateWithoutLoanInput>
}

export type DeductionUpdateWithWhereUniqueWithoutLoanInput = {
  where: Prisma.DeductionWhereUniqueInput
  data: Prisma.XOR<Prisma.DeductionUpdateWithoutLoanInput, Prisma.DeductionUncheckedUpdateWithoutLoanInput>
}

export type DeductionUpdateManyWithWhereWithoutLoanInput = {
  where: Prisma.DeductionScalarWhereInput
  data: Prisma.XOR<Prisma.DeductionUpdateManyMutationInput, Prisma.DeductionUncheckedUpdateManyWithoutLoanInput>
}

export type DeductionCreateWithoutPenaltyInput = {
  id?: string
  loanType?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  saving: Prisma.SavingCreateNestedOneWithoutDeductionsInput
  loan?: Prisma.LoanCreateNestedOneWithoutDeductionsInput
}

export type DeductionUncheckedCreateWithoutPenaltyInput = {
  id?: string
  savingId: string
  loanId?: string | null
  loanType?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DeductionCreateOrConnectWithoutPenaltyInput = {
  where: Prisma.DeductionWhereUniqueInput
  create: Prisma.XOR<Prisma.DeductionCreateWithoutPenaltyInput, Prisma.DeductionUncheckedCreateWithoutPenaltyInput>
}

export type DeductionCreateManyPenaltyInputEnvelope = {
  data: Prisma.DeductionCreateManyPenaltyInput | Prisma.DeductionCreateManyPenaltyInput[]
  skipDuplicates?: boolean
}

export type DeductionUpsertWithWhereUniqueWithoutPenaltyInput = {
  where: Prisma.DeductionWhereUniqueInput
  update: Prisma.XOR<Prisma.DeductionUpdateWithoutPenaltyInput, Prisma.DeductionUncheckedUpdateWithoutPenaltyInput>
  create: Prisma.XOR<Prisma.DeductionCreateWithoutPenaltyInput, Prisma.DeductionUncheckedCreateWithoutPenaltyInput>
}

export type DeductionUpdateWithWhereUniqueWithoutPenaltyInput = {
  where: Prisma.DeductionWhereUniqueInput
  data: Prisma.XOR<Prisma.DeductionUpdateWithoutPenaltyInput, Prisma.DeductionUncheckedUpdateWithoutPenaltyInput>
}

export type DeductionUpdateManyWithWhereWithoutPenaltyInput = {
  where: Prisma.DeductionScalarWhereInput
  data: Prisma.XOR<Prisma.DeductionUpdateManyMutationInput, Prisma.DeductionUncheckedUpdateManyWithoutPenaltyInput>
}

export type DeductionCreateManySavingInput = {
  id?: string
  loanId?: string | null
  loanType?: string | null
  penaltyId?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DeductionUpdateWithoutSavingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  loan?: Prisma.LoanUpdateOneWithoutDeductionsNestedInput
  penalty?: Prisma.PenaltyUpdateOneWithoutDeductionsNestedInput
}

export type DeductionUncheckedUpdateWithoutSavingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeductionUncheckedUpdateManyWithoutSavingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeductionCreateManyLoanInput = {
  id?: string
  savingId: string
  loanType?: string | null
  penaltyId?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DeductionUpdateWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  saving?: Prisma.SavingUpdateOneRequiredWithoutDeductionsNestedInput
  penalty?: Prisma.PenaltyUpdateOneWithoutDeductionsNestedInput
}

export type DeductionUncheckedUpdateWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  savingId?: Prisma.StringFieldUpdateOperationsInput | string
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeductionUncheckedUpdateManyWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  savingId?: Prisma.StringFieldUpdateOperationsInput | string
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeductionCreateManyPenaltyInput = {
  id?: string
  savingId: string
  loanId?: string | null
  loanType?: string | null
  amount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DeductionUpdateWithoutPenaltyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  saving?: Prisma.SavingUpdateOneRequiredWithoutDeductionsNestedInput
  loan?: Prisma.LoanUpdateOneWithoutDeductionsNestedInput
}

export type DeductionUncheckedUpdateWithoutPenaltyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  savingId?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeductionUncheckedUpdateManyWithoutPenaltyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  savingId?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DeductionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  savingId?: boolean
  loanId?: boolean
  loanType?: boolean
  penaltyId?: boolean
  amount?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  saving?: boolean | Prisma.SavingDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Deduction$loanArgs<ExtArgs>
  penalty?: boolean | Prisma.Deduction$penaltyArgs<ExtArgs>
}, ExtArgs["result"]["deduction"]>

export type DeductionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  savingId?: boolean
  loanId?: boolean
  loanType?: boolean
  penaltyId?: boolean
  amount?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  saving?: boolean | Prisma.SavingDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Deduction$loanArgs<ExtArgs>
  penalty?: boolean | Prisma.Deduction$penaltyArgs<ExtArgs>
}, ExtArgs["result"]["deduction"]>

export type DeductionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  savingId?: boolean
  loanId?: boolean
  loanType?: boolean
  penaltyId?: boolean
  amount?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  saving?: boolean | Prisma.SavingDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Deduction$loanArgs<ExtArgs>
  penalty?: boolean | Prisma.Deduction$penaltyArgs<ExtArgs>
}, ExtArgs["result"]["deduction"]>

export type DeductionSelectScalar = {
  id?: boolean
  savingId?: boolean
  loanId?: boolean
  loanType?: boolean
  penaltyId?: boolean
  amount?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DeductionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "savingId" | "loanId" | "loanType" | "penaltyId" | "amount" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["deduction"]>
export type DeductionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  saving?: boolean | Prisma.SavingDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Deduction$loanArgs<ExtArgs>
  penalty?: boolean | Prisma.Deduction$penaltyArgs<ExtArgs>
}
export type DeductionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  saving?: boolean | Prisma.SavingDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Deduction$loanArgs<ExtArgs>
  penalty?: boolean | Prisma.Deduction$penaltyArgs<ExtArgs>
}
export type DeductionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  saving?: boolean | Prisma.SavingDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Deduction$loanArgs<ExtArgs>
  penalty?: boolean | Prisma.Deduction$penaltyArgs<ExtArgs>
}

export type $DeductionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Deduction"
  objects: {
    saving: Prisma.$SavingPayload<ExtArgs>
    loan: Prisma.$LoanPayload<ExtArgs> | null
    penalty: Prisma.$PenaltyPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    savingId: string
    loanId: string | null
    loanType: string | null
    penaltyId: string | null
    amount: number
    status: $Enums.TransactionStatus
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["deduction"]>
  composites: {}
}

export type DeductionGetPayload<S extends boolean | null | undefined | DeductionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DeductionPayload, S>

export type DeductionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DeductionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DeductionCountAggregateInputType | true
  }

export interface DeductionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Deduction'], meta: { name: 'Deduction' } }
  /**
   * Find zero or one Deduction that matches the filter.
   * @param {DeductionFindUniqueArgs} args - Arguments to find a Deduction
   * @example
   * // Get one Deduction
   * const deduction = await prisma.deduction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DeductionFindUniqueArgs>(args: Prisma.SelectSubset<T, DeductionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DeductionClient<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Deduction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DeductionFindUniqueOrThrowArgs} args - Arguments to find a Deduction
   * @example
   * // Get one Deduction
   * const deduction = await prisma.deduction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DeductionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DeductionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DeductionClient<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Deduction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeductionFindFirstArgs} args - Arguments to find a Deduction
   * @example
   * // Get one Deduction
   * const deduction = await prisma.deduction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DeductionFindFirstArgs>(args?: Prisma.SelectSubset<T, DeductionFindFirstArgs<ExtArgs>>): Prisma.Prisma__DeductionClient<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Deduction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeductionFindFirstOrThrowArgs} args - Arguments to find a Deduction
   * @example
   * // Get one Deduction
   * const deduction = await prisma.deduction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DeductionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DeductionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DeductionClient<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Deductions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeductionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Deductions
   * const deductions = await prisma.deduction.findMany()
   * 
   * // Get first 10 Deductions
   * const deductions = await prisma.deduction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const deductionWithIdOnly = await prisma.deduction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DeductionFindManyArgs>(args?: Prisma.SelectSubset<T, DeductionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Deduction.
   * @param {DeductionCreateArgs} args - Arguments to create a Deduction.
   * @example
   * // Create one Deduction
   * const Deduction = await prisma.deduction.create({
   *   data: {
   *     // ... data to create a Deduction
   *   }
   * })
   * 
   */
  create<T extends DeductionCreateArgs>(args: Prisma.SelectSubset<T, DeductionCreateArgs<ExtArgs>>): Prisma.Prisma__DeductionClient<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Deductions.
   * @param {DeductionCreateManyArgs} args - Arguments to create many Deductions.
   * @example
   * // Create many Deductions
   * const deduction = await prisma.deduction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DeductionCreateManyArgs>(args?: Prisma.SelectSubset<T, DeductionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Deductions and returns the data saved in the database.
   * @param {DeductionCreateManyAndReturnArgs} args - Arguments to create many Deductions.
   * @example
   * // Create many Deductions
   * const deduction = await prisma.deduction.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Deductions and only return the `id`
   * const deductionWithIdOnly = await prisma.deduction.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DeductionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DeductionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Deduction.
   * @param {DeductionDeleteArgs} args - Arguments to delete one Deduction.
   * @example
   * // Delete one Deduction
   * const Deduction = await prisma.deduction.delete({
   *   where: {
   *     // ... filter to delete one Deduction
   *   }
   * })
   * 
   */
  delete<T extends DeductionDeleteArgs>(args: Prisma.SelectSubset<T, DeductionDeleteArgs<ExtArgs>>): Prisma.Prisma__DeductionClient<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Deduction.
   * @param {DeductionUpdateArgs} args - Arguments to update one Deduction.
   * @example
   * // Update one Deduction
   * const deduction = await prisma.deduction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DeductionUpdateArgs>(args: Prisma.SelectSubset<T, DeductionUpdateArgs<ExtArgs>>): Prisma.Prisma__DeductionClient<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Deductions.
   * @param {DeductionDeleteManyArgs} args - Arguments to filter Deductions to delete.
   * @example
   * // Delete a few Deductions
   * const { count } = await prisma.deduction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DeductionDeleteManyArgs>(args?: Prisma.SelectSubset<T, DeductionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Deductions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeductionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Deductions
   * const deduction = await prisma.deduction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DeductionUpdateManyArgs>(args: Prisma.SelectSubset<T, DeductionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Deductions and returns the data updated in the database.
   * @param {DeductionUpdateManyAndReturnArgs} args - Arguments to update many Deductions.
   * @example
   * // Update many Deductions
   * const deduction = await prisma.deduction.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Deductions and only return the `id`
   * const deductionWithIdOnly = await prisma.deduction.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DeductionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DeductionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Deduction.
   * @param {DeductionUpsertArgs} args - Arguments to update or create a Deduction.
   * @example
   * // Update or create a Deduction
   * const deduction = await prisma.deduction.upsert({
   *   create: {
   *     // ... data to create a Deduction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Deduction we want to update
   *   }
   * })
   */
  upsert<T extends DeductionUpsertArgs>(args: Prisma.SelectSubset<T, DeductionUpsertArgs<ExtArgs>>): Prisma.Prisma__DeductionClient<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Deductions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeductionCountArgs} args - Arguments to filter Deductions to count.
   * @example
   * // Count the number of Deductions
   * const count = await prisma.deduction.count({
   *   where: {
   *     // ... the filter for the Deductions we want to count
   *   }
   * })
  **/
  count<T extends DeductionCountArgs>(
    args?: Prisma.Subset<T, DeductionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DeductionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Deduction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeductionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DeductionAggregateArgs>(args: Prisma.Subset<T, DeductionAggregateArgs>): Prisma.PrismaPromise<GetDeductionAggregateType<T>>

  /**
   * Group by Deduction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeductionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DeductionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DeductionGroupByArgs['orderBy'] }
      : { orderBy?: DeductionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DeductionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDeductionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Deduction model
 */
readonly fields: DeductionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Deduction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DeductionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  saving<T extends Prisma.SavingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SavingDefaultArgs<ExtArgs>>): Prisma.Prisma__SavingClient<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  loan<T extends Prisma.Deduction$loanArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Deduction$loanArgs<ExtArgs>>): Prisma.Prisma__LoanClient<runtime.Types.Result.GetResult<Prisma.$LoanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  penalty<T extends Prisma.Deduction$penaltyArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Deduction$penaltyArgs<ExtArgs>>): Prisma.Prisma__PenaltyClient<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Deduction model
 */
export interface DeductionFieldRefs {
  readonly id: Prisma.FieldRef<"Deduction", 'String'>
  readonly savingId: Prisma.FieldRef<"Deduction", 'String'>
  readonly loanId: Prisma.FieldRef<"Deduction", 'String'>
  readonly loanType: Prisma.FieldRef<"Deduction", 'String'>
  readonly penaltyId: Prisma.FieldRef<"Deduction", 'String'>
  readonly amount: Prisma.FieldRef<"Deduction", 'Float'>
  readonly status: Prisma.FieldRef<"Deduction", 'TransactionStatus'>
  readonly createdAt: Prisma.FieldRef<"Deduction", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Deduction", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Deduction findUnique
 */
export type DeductionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionInclude<ExtArgs> | null
  /**
   * Filter, which Deduction to fetch.
   */
  where: Prisma.DeductionWhereUniqueInput
}

/**
 * Deduction findUniqueOrThrow
 */
export type DeductionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionInclude<ExtArgs> | null
  /**
   * Filter, which Deduction to fetch.
   */
  where: Prisma.DeductionWhereUniqueInput
}

/**
 * Deduction findFirst
 */
export type DeductionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionInclude<ExtArgs> | null
  /**
   * Filter, which Deduction to fetch.
   */
  where?: Prisma.DeductionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Deductions to fetch.
   */
  orderBy?: Prisma.DeductionOrderByWithRelationInput | Prisma.DeductionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Deductions.
   */
  cursor?: Prisma.DeductionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Deductions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Deductions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Deductions.
   */
  distinct?: Prisma.DeductionScalarFieldEnum | Prisma.DeductionScalarFieldEnum[]
}

/**
 * Deduction findFirstOrThrow
 */
export type DeductionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionInclude<ExtArgs> | null
  /**
   * Filter, which Deduction to fetch.
   */
  where?: Prisma.DeductionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Deductions to fetch.
   */
  orderBy?: Prisma.DeductionOrderByWithRelationInput | Prisma.DeductionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Deductions.
   */
  cursor?: Prisma.DeductionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Deductions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Deductions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Deductions.
   */
  distinct?: Prisma.DeductionScalarFieldEnum | Prisma.DeductionScalarFieldEnum[]
}

/**
 * Deduction findMany
 */
export type DeductionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionInclude<ExtArgs> | null
  /**
   * Filter, which Deductions to fetch.
   */
  where?: Prisma.DeductionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Deductions to fetch.
   */
  orderBy?: Prisma.DeductionOrderByWithRelationInput | Prisma.DeductionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Deductions.
   */
  cursor?: Prisma.DeductionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Deductions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Deductions.
   */
  skip?: number
  distinct?: Prisma.DeductionScalarFieldEnum | Prisma.DeductionScalarFieldEnum[]
}

/**
 * Deduction create
 */
export type DeductionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionInclude<ExtArgs> | null
  /**
   * The data needed to create a Deduction.
   */
  data: Prisma.XOR<Prisma.DeductionCreateInput, Prisma.DeductionUncheckedCreateInput>
}

/**
 * Deduction createMany
 */
export type DeductionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Deductions.
   */
  data: Prisma.DeductionCreateManyInput | Prisma.DeductionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Deduction createManyAndReturn
 */
export type DeductionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * The data used to create many Deductions.
   */
  data: Prisma.DeductionCreateManyInput | Prisma.DeductionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Deduction update
 */
export type DeductionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionInclude<ExtArgs> | null
  /**
   * The data needed to update a Deduction.
   */
  data: Prisma.XOR<Prisma.DeductionUpdateInput, Prisma.DeductionUncheckedUpdateInput>
  /**
   * Choose, which Deduction to update.
   */
  where: Prisma.DeductionWhereUniqueInput
}

/**
 * Deduction updateMany
 */
export type DeductionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Deductions.
   */
  data: Prisma.XOR<Prisma.DeductionUpdateManyMutationInput, Prisma.DeductionUncheckedUpdateManyInput>
  /**
   * Filter which Deductions to update
   */
  where?: Prisma.DeductionWhereInput
  /**
   * Limit how many Deductions to update.
   */
  limit?: number
}

/**
 * Deduction updateManyAndReturn
 */
export type DeductionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * The data used to update Deductions.
   */
  data: Prisma.XOR<Prisma.DeductionUpdateManyMutationInput, Prisma.DeductionUncheckedUpdateManyInput>
  /**
   * Filter which Deductions to update
   */
  where?: Prisma.DeductionWhereInput
  /**
   * Limit how many Deductions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Deduction upsert
 */
export type DeductionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionInclude<ExtArgs> | null
  /**
   * The filter to search for the Deduction to update in case it exists.
   */
  where: Prisma.DeductionWhereUniqueInput
  /**
   * In case the Deduction found by the `where` argument doesn't exist, create a new Deduction with this data.
   */
  create: Prisma.XOR<Prisma.DeductionCreateInput, Prisma.DeductionUncheckedCreateInput>
  /**
   * In case the Deduction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DeductionUpdateInput, Prisma.DeductionUncheckedUpdateInput>
}

/**
 * Deduction delete
 */
export type DeductionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionInclude<ExtArgs> | null
  /**
   * Filter which Deduction to delete.
   */
  where: Prisma.DeductionWhereUniqueInput
}

/**
 * Deduction deleteMany
 */
export type DeductionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Deductions to delete
   */
  where?: Prisma.DeductionWhereInput
  /**
   * Limit how many Deductions to delete.
   */
  limit?: number
}

/**
 * Deduction.loan
 */
export type Deduction$loanArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Loan
   */
  select?: Prisma.LoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Loan
   */
  omit?: Prisma.LoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanInclude<ExtArgs> | null
  where?: Prisma.LoanWhereInput
}

/**
 * Deduction.penalty
 */
export type Deduction$penaltyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
  where?: Prisma.PenaltyWhereInput
}

/**
 * Deduction without action
 */
export type DeductionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionInclude<ExtArgs> | null
}
