
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Penalty` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Penalty
 * 
 */
export type PenaltyModel = runtime.Types.Result.DefaultSelection<Prisma.$PenaltyPayload>

export type AggregatePenalty = {
  _count: PenaltyCountAggregateOutputType | null
  _avg: PenaltyAvgAggregateOutputType | null
  _sum: PenaltySumAggregateOutputType | null
  _min: PenaltyMinAggregateOutputType | null
  _max: PenaltyMaxAggregateOutputType | null
}

export type PenaltyAvgAggregateOutputType = {
  penaltyAmount: number | null
}

export type PenaltySumAggregateOutputType = {
  penaltyAmount: number | null
}

export type PenaltyMinAggregateOutputType = {
  id: string | null
  memberId: string | null
  loanId: string | null
  shortLoanId: string | null
  penaltyAmount: number | null
  status: $Enums.TransactionStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PenaltyMaxAggregateOutputType = {
  id: string | null
  memberId: string | null
  loanId: string | null
  shortLoanId: string | null
  penaltyAmount: number | null
  status: $Enums.TransactionStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PenaltyCountAggregateOutputType = {
  id: number
  memberId: number
  loanId: number
  shortLoanId: number
  penaltyAmount: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PenaltyAvgAggregateInputType = {
  penaltyAmount?: true
}

export type PenaltySumAggregateInputType = {
  penaltyAmount?: true
}

export type PenaltyMinAggregateInputType = {
  id?: true
  memberId?: true
  loanId?: true
  shortLoanId?: true
  penaltyAmount?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type PenaltyMaxAggregateInputType = {
  id?: true
  memberId?: true
  loanId?: true
  shortLoanId?: true
  penaltyAmount?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type PenaltyCountAggregateInputType = {
  id?: true
  memberId?: true
  loanId?: true
  shortLoanId?: true
  penaltyAmount?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PenaltyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Penalty to aggregate.
   */
  where?: Prisma.PenaltyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Penalties to fetch.
   */
  orderBy?: Prisma.PenaltyOrderByWithRelationInput | Prisma.PenaltyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PenaltyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Penalties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Penalties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Penalties
  **/
  _count?: true | PenaltyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PenaltyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PenaltySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PenaltyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PenaltyMaxAggregateInputType
}

export type GetPenaltyAggregateType<T extends PenaltyAggregateArgs> = {
      [P in keyof T & keyof AggregatePenalty]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePenalty[P]>
    : Prisma.GetScalarType<T[P], AggregatePenalty[P]>
}




export type PenaltyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PenaltyWhereInput
  orderBy?: Prisma.PenaltyOrderByWithAggregationInput | Prisma.PenaltyOrderByWithAggregationInput[]
  by: Prisma.PenaltyScalarFieldEnum[] | Prisma.PenaltyScalarFieldEnum
  having?: Prisma.PenaltyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PenaltyCountAggregateInputType | true
  _avg?: PenaltyAvgAggregateInputType
  _sum?: PenaltySumAggregateInputType
  _min?: PenaltyMinAggregateInputType
  _max?: PenaltyMaxAggregateInputType
}

export type PenaltyGroupByOutputType = {
  id: string
  memberId: string
  loanId: string | null
  shortLoanId: string | null
  penaltyAmount: number
  status: $Enums.TransactionStatus
  createdAt: Date
  updatedAt: Date
  _count: PenaltyCountAggregateOutputType | null
  _avg: PenaltyAvgAggregateOutputType | null
  _sum: PenaltySumAggregateOutputType | null
  _min: PenaltyMinAggregateOutputType | null
  _max: PenaltyMaxAggregateOutputType | null
}

type GetPenaltyGroupByPayload<T extends PenaltyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PenaltyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PenaltyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PenaltyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PenaltyGroupByOutputType[P]>
      }
    >
  >



export type PenaltyWhereInput = {
  AND?: Prisma.PenaltyWhereInput | Prisma.PenaltyWhereInput[]
  OR?: Prisma.PenaltyWhereInput[]
  NOT?: Prisma.PenaltyWhereInput | Prisma.PenaltyWhereInput[]
  id?: Prisma.StringFilter<"Penalty"> | string
  memberId?: Prisma.StringFilter<"Penalty"> | string
  loanId?: Prisma.StringNullableFilter<"Penalty"> | string | null
  shortLoanId?: Prisma.StringNullableFilter<"Penalty"> | string | null
  penaltyAmount?: Prisma.FloatFilter<"Penalty"> | number
  status?: Prisma.EnumTransactionStatusFilter<"Penalty"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"Penalty"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Penalty"> | Date | string
  member?: Prisma.XOR<Prisma.MemberScalarRelationFilter, Prisma.MemberWhereInput>
  loan?: Prisma.XOR<Prisma.LoanNullableScalarRelationFilter, Prisma.LoanWhereInput> | null
  shortLoan?: Prisma.XOR<Prisma.ShortLoanNullableScalarRelationFilter, Prisma.ShortLoanWhereInput> | null
  savings?: Prisma.SavingListRelationFilter
}

export type PenaltyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  loanId?: Prisma.SortOrderInput | Prisma.SortOrder
  shortLoanId?: Prisma.SortOrderInput | Prisma.SortOrder
  penaltyAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  member?: Prisma.MemberOrderByWithRelationInput
  loan?: Prisma.LoanOrderByWithRelationInput
  shortLoan?: Prisma.ShortLoanOrderByWithRelationInput
  savings?: Prisma.SavingOrderByRelationAggregateInput
}

export type PenaltyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PenaltyWhereInput | Prisma.PenaltyWhereInput[]
  OR?: Prisma.PenaltyWhereInput[]
  NOT?: Prisma.PenaltyWhereInput | Prisma.PenaltyWhereInput[]
  memberId?: Prisma.StringFilter<"Penalty"> | string
  loanId?: Prisma.StringNullableFilter<"Penalty"> | string | null
  shortLoanId?: Prisma.StringNullableFilter<"Penalty"> | string | null
  penaltyAmount?: Prisma.FloatFilter<"Penalty"> | number
  status?: Prisma.EnumTransactionStatusFilter<"Penalty"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"Penalty"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Penalty"> | Date | string
  member?: Prisma.XOR<Prisma.MemberScalarRelationFilter, Prisma.MemberWhereInput>
  loan?: Prisma.XOR<Prisma.LoanNullableScalarRelationFilter, Prisma.LoanWhereInput> | null
  shortLoan?: Prisma.XOR<Prisma.ShortLoanNullableScalarRelationFilter, Prisma.ShortLoanWhereInput> | null
  savings?: Prisma.SavingListRelationFilter
}, "id">

export type PenaltyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  loanId?: Prisma.SortOrderInput | Prisma.SortOrder
  shortLoanId?: Prisma.SortOrderInput | Prisma.SortOrder
  penaltyAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PenaltyCountOrderByAggregateInput
  _avg?: Prisma.PenaltyAvgOrderByAggregateInput
  _max?: Prisma.PenaltyMaxOrderByAggregateInput
  _min?: Prisma.PenaltyMinOrderByAggregateInput
  _sum?: Prisma.PenaltySumOrderByAggregateInput
}

export type PenaltyScalarWhereWithAggregatesInput = {
  AND?: Prisma.PenaltyScalarWhereWithAggregatesInput | Prisma.PenaltyScalarWhereWithAggregatesInput[]
  OR?: Prisma.PenaltyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PenaltyScalarWhereWithAggregatesInput | Prisma.PenaltyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Penalty"> | string
  memberId?: Prisma.StringWithAggregatesFilter<"Penalty"> | string
  loanId?: Prisma.StringNullableWithAggregatesFilter<"Penalty"> | string | null
  shortLoanId?: Prisma.StringNullableWithAggregatesFilter<"Penalty"> | string | null
  penaltyAmount?: Prisma.FloatWithAggregatesFilter<"Penalty"> | number
  status?: Prisma.EnumTransactionStatusWithAggregatesFilter<"Penalty"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Penalty"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Penalty"> | Date | string
}

export type PenaltyCreateInput = {
  id?: string
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutPenaltiesInput
  loan?: Prisma.LoanCreateNestedOneWithoutPenaltiesInput
  shortLoan?: Prisma.ShortLoanCreateNestedOneWithoutPenaltiesInput
  savings?: Prisma.SavingCreateNestedManyWithoutPenaltyInput
}

export type PenaltyUncheckedCreateInput = {
  id?: string
  memberId: string
  loanId?: string | null
  shortLoanId?: string | null
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  savings?: Prisma.SavingUncheckedCreateNestedManyWithoutPenaltyInput
}

export type PenaltyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutPenaltiesNestedInput
  loan?: Prisma.LoanUpdateOneWithoutPenaltiesNestedInput
  shortLoan?: Prisma.ShortLoanUpdateOneWithoutPenaltiesNestedInput
  savings?: Prisma.SavingUpdateManyWithoutPenaltyNestedInput
}

export type PenaltyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  savings?: Prisma.SavingUncheckedUpdateManyWithoutPenaltyNestedInput
}

export type PenaltyCreateManyInput = {
  id?: string
  memberId: string
  loanId?: string | null
  shortLoanId?: string | null
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PenaltyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PenaltyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PenaltyListRelationFilter = {
  every?: Prisma.PenaltyWhereInput
  some?: Prisma.PenaltyWhereInput
  none?: Prisma.PenaltyWhereInput
}

export type PenaltyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PenaltyNullableScalarRelationFilter = {
  is?: Prisma.PenaltyWhereInput | null
  isNot?: Prisma.PenaltyWhereInput | null
}

export type PenaltyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  shortLoanId?: Prisma.SortOrder
  penaltyAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PenaltyAvgOrderByAggregateInput = {
  penaltyAmount?: Prisma.SortOrder
}

export type PenaltyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  shortLoanId?: Prisma.SortOrder
  penaltyAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PenaltyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  shortLoanId?: Prisma.SortOrder
  penaltyAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PenaltySumOrderByAggregateInput = {
  penaltyAmount?: Prisma.SortOrder
}

export type PenaltyCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutMemberInput, Prisma.PenaltyUncheckedCreateWithoutMemberInput> | Prisma.PenaltyCreateWithoutMemberInput[] | Prisma.PenaltyUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutMemberInput | Prisma.PenaltyCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.PenaltyCreateManyMemberInputEnvelope
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
}

export type PenaltyUncheckedCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutMemberInput, Prisma.PenaltyUncheckedCreateWithoutMemberInput> | Prisma.PenaltyCreateWithoutMemberInput[] | Prisma.PenaltyUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutMemberInput | Prisma.PenaltyCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.PenaltyCreateManyMemberInputEnvelope
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
}

export type PenaltyUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutMemberInput, Prisma.PenaltyUncheckedCreateWithoutMemberInput> | Prisma.PenaltyCreateWithoutMemberInput[] | Prisma.PenaltyUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutMemberInput | Prisma.PenaltyCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.PenaltyUpsertWithWhereUniqueWithoutMemberInput | Prisma.PenaltyUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.PenaltyCreateManyMemberInputEnvelope
  set?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  disconnect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  delete?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  update?: Prisma.PenaltyUpdateWithWhereUniqueWithoutMemberInput | Prisma.PenaltyUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.PenaltyUpdateManyWithWhereWithoutMemberInput | Prisma.PenaltyUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.PenaltyScalarWhereInput | Prisma.PenaltyScalarWhereInput[]
}

export type PenaltyUncheckedUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutMemberInput, Prisma.PenaltyUncheckedCreateWithoutMemberInput> | Prisma.PenaltyCreateWithoutMemberInput[] | Prisma.PenaltyUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutMemberInput | Prisma.PenaltyCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.PenaltyUpsertWithWhereUniqueWithoutMemberInput | Prisma.PenaltyUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.PenaltyCreateManyMemberInputEnvelope
  set?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  disconnect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  delete?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  update?: Prisma.PenaltyUpdateWithWhereUniqueWithoutMemberInput | Prisma.PenaltyUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.PenaltyUpdateManyWithWhereWithoutMemberInput | Prisma.PenaltyUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.PenaltyScalarWhereInput | Prisma.PenaltyScalarWhereInput[]
}

export type PenaltyCreateNestedOneWithoutSavingsInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutSavingsInput, Prisma.PenaltyUncheckedCreateWithoutSavingsInput>
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutSavingsInput
  connect?: Prisma.PenaltyWhereUniqueInput
}

export type PenaltyUpdateOneWithoutSavingsNestedInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutSavingsInput, Prisma.PenaltyUncheckedCreateWithoutSavingsInput>
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutSavingsInput
  upsert?: Prisma.PenaltyUpsertWithoutSavingsInput
  disconnect?: Prisma.PenaltyWhereInput | boolean
  delete?: Prisma.PenaltyWhereInput | boolean
  connect?: Prisma.PenaltyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PenaltyUpdateToOneWithWhereWithoutSavingsInput, Prisma.PenaltyUpdateWithoutSavingsInput>, Prisma.PenaltyUncheckedUpdateWithoutSavingsInput>
}

export type PenaltyCreateNestedManyWithoutLoanInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutLoanInput, Prisma.PenaltyUncheckedCreateWithoutLoanInput> | Prisma.PenaltyCreateWithoutLoanInput[] | Prisma.PenaltyUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutLoanInput | Prisma.PenaltyCreateOrConnectWithoutLoanInput[]
  createMany?: Prisma.PenaltyCreateManyLoanInputEnvelope
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
}

export type PenaltyUncheckedCreateNestedManyWithoutLoanInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutLoanInput, Prisma.PenaltyUncheckedCreateWithoutLoanInput> | Prisma.PenaltyCreateWithoutLoanInput[] | Prisma.PenaltyUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutLoanInput | Prisma.PenaltyCreateOrConnectWithoutLoanInput[]
  createMany?: Prisma.PenaltyCreateManyLoanInputEnvelope
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
}

export type PenaltyUpdateManyWithoutLoanNestedInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutLoanInput, Prisma.PenaltyUncheckedCreateWithoutLoanInput> | Prisma.PenaltyCreateWithoutLoanInput[] | Prisma.PenaltyUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutLoanInput | Prisma.PenaltyCreateOrConnectWithoutLoanInput[]
  upsert?: Prisma.PenaltyUpsertWithWhereUniqueWithoutLoanInput | Prisma.PenaltyUpsertWithWhereUniqueWithoutLoanInput[]
  createMany?: Prisma.PenaltyCreateManyLoanInputEnvelope
  set?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  disconnect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  delete?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  update?: Prisma.PenaltyUpdateWithWhereUniqueWithoutLoanInput | Prisma.PenaltyUpdateWithWhereUniqueWithoutLoanInput[]
  updateMany?: Prisma.PenaltyUpdateManyWithWhereWithoutLoanInput | Prisma.PenaltyUpdateManyWithWhereWithoutLoanInput[]
  deleteMany?: Prisma.PenaltyScalarWhereInput | Prisma.PenaltyScalarWhereInput[]
}

export type PenaltyUncheckedUpdateManyWithoutLoanNestedInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutLoanInput, Prisma.PenaltyUncheckedCreateWithoutLoanInput> | Prisma.PenaltyCreateWithoutLoanInput[] | Prisma.PenaltyUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutLoanInput | Prisma.PenaltyCreateOrConnectWithoutLoanInput[]
  upsert?: Prisma.PenaltyUpsertWithWhereUniqueWithoutLoanInput | Prisma.PenaltyUpsertWithWhereUniqueWithoutLoanInput[]
  createMany?: Prisma.PenaltyCreateManyLoanInputEnvelope
  set?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  disconnect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  delete?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  update?: Prisma.PenaltyUpdateWithWhereUniqueWithoutLoanInput | Prisma.PenaltyUpdateWithWhereUniqueWithoutLoanInput[]
  updateMany?: Prisma.PenaltyUpdateManyWithWhereWithoutLoanInput | Prisma.PenaltyUpdateManyWithWhereWithoutLoanInput[]
  deleteMany?: Prisma.PenaltyScalarWhereInput | Prisma.PenaltyScalarWhereInput[]
}

export type PenaltyCreateNestedManyWithoutShortLoanInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutShortLoanInput, Prisma.PenaltyUncheckedCreateWithoutShortLoanInput> | Prisma.PenaltyCreateWithoutShortLoanInput[] | Prisma.PenaltyUncheckedCreateWithoutShortLoanInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutShortLoanInput | Prisma.PenaltyCreateOrConnectWithoutShortLoanInput[]
  createMany?: Prisma.PenaltyCreateManyShortLoanInputEnvelope
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
}

export type PenaltyUncheckedCreateNestedManyWithoutShortLoanInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutShortLoanInput, Prisma.PenaltyUncheckedCreateWithoutShortLoanInput> | Prisma.PenaltyCreateWithoutShortLoanInput[] | Prisma.PenaltyUncheckedCreateWithoutShortLoanInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutShortLoanInput | Prisma.PenaltyCreateOrConnectWithoutShortLoanInput[]
  createMany?: Prisma.PenaltyCreateManyShortLoanInputEnvelope
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
}

export type PenaltyUpdateManyWithoutShortLoanNestedInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutShortLoanInput, Prisma.PenaltyUncheckedCreateWithoutShortLoanInput> | Prisma.PenaltyCreateWithoutShortLoanInput[] | Prisma.PenaltyUncheckedCreateWithoutShortLoanInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutShortLoanInput | Prisma.PenaltyCreateOrConnectWithoutShortLoanInput[]
  upsert?: Prisma.PenaltyUpsertWithWhereUniqueWithoutShortLoanInput | Prisma.PenaltyUpsertWithWhereUniqueWithoutShortLoanInput[]
  createMany?: Prisma.PenaltyCreateManyShortLoanInputEnvelope
  set?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  disconnect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  delete?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  update?: Prisma.PenaltyUpdateWithWhereUniqueWithoutShortLoanInput | Prisma.PenaltyUpdateWithWhereUniqueWithoutShortLoanInput[]
  updateMany?: Prisma.PenaltyUpdateManyWithWhereWithoutShortLoanInput | Prisma.PenaltyUpdateManyWithWhereWithoutShortLoanInput[]
  deleteMany?: Prisma.PenaltyScalarWhereInput | Prisma.PenaltyScalarWhereInput[]
}

export type PenaltyUncheckedUpdateManyWithoutShortLoanNestedInput = {
  create?: Prisma.XOR<Prisma.PenaltyCreateWithoutShortLoanInput, Prisma.PenaltyUncheckedCreateWithoutShortLoanInput> | Prisma.PenaltyCreateWithoutShortLoanInput[] | Prisma.PenaltyUncheckedCreateWithoutShortLoanInput[]
  connectOrCreate?: Prisma.PenaltyCreateOrConnectWithoutShortLoanInput | Prisma.PenaltyCreateOrConnectWithoutShortLoanInput[]
  upsert?: Prisma.PenaltyUpsertWithWhereUniqueWithoutShortLoanInput | Prisma.PenaltyUpsertWithWhereUniqueWithoutShortLoanInput[]
  createMany?: Prisma.PenaltyCreateManyShortLoanInputEnvelope
  set?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  disconnect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  delete?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  connect?: Prisma.PenaltyWhereUniqueInput | Prisma.PenaltyWhereUniqueInput[]
  update?: Prisma.PenaltyUpdateWithWhereUniqueWithoutShortLoanInput | Prisma.PenaltyUpdateWithWhereUniqueWithoutShortLoanInput[]
  updateMany?: Prisma.PenaltyUpdateManyWithWhereWithoutShortLoanInput | Prisma.PenaltyUpdateManyWithWhereWithoutShortLoanInput[]
  deleteMany?: Prisma.PenaltyScalarWhereInput | Prisma.PenaltyScalarWhereInput[]
}

export type PenaltyCreateWithoutMemberInput = {
  id?: string
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  loan?: Prisma.LoanCreateNestedOneWithoutPenaltiesInput
  shortLoan?: Prisma.ShortLoanCreateNestedOneWithoutPenaltiesInput
  savings?: Prisma.SavingCreateNestedManyWithoutPenaltyInput
}

export type PenaltyUncheckedCreateWithoutMemberInput = {
  id?: string
  loanId?: string | null
  shortLoanId?: string | null
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  savings?: Prisma.SavingUncheckedCreateNestedManyWithoutPenaltyInput
}

export type PenaltyCreateOrConnectWithoutMemberInput = {
  where: Prisma.PenaltyWhereUniqueInput
  create: Prisma.XOR<Prisma.PenaltyCreateWithoutMemberInput, Prisma.PenaltyUncheckedCreateWithoutMemberInput>
}

export type PenaltyCreateManyMemberInputEnvelope = {
  data: Prisma.PenaltyCreateManyMemberInput | Prisma.PenaltyCreateManyMemberInput[]
  skipDuplicates?: boolean
}

export type PenaltyUpsertWithWhereUniqueWithoutMemberInput = {
  where: Prisma.PenaltyWhereUniqueInput
  update: Prisma.XOR<Prisma.PenaltyUpdateWithoutMemberInput, Prisma.PenaltyUncheckedUpdateWithoutMemberInput>
  create: Prisma.XOR<Prisma.PenaltyCreateWithoutMemberInput, Prisma.PenaltyUncheckedCreateWithoutMemberInput>
}

export type PenaltyUpdateWithWhereUniqueWithoutMemberInput = {
  where: Prisma.PenaltyWhereUniqueInput
  data: Prisma.XOR<Prisma.PenaltyUpdateWithoutMemberInput, Prisma.PenaltyUncheckedUpdateWithoutMemberInput>
}

export type PenaltyUpdateManyWithWhereWithoutMemberInput = {
  where: Prisma.PenaltyScalarWhereInput
  data: Prisma.XOR<Prisma.PenaltyUpdateManyMutationInput, Prisma.PenaltyUncheckedUpdateManyWithoutMemberInput>
}

export type PenaltyScalarWhereInput = {
  AND?: Prisma.PenaltyScalarWhereInput | Prisma.PenaltyScalarWhereInput[]
  OR?: Prisma.PenaltyScalarWhereInput[]
  NOT?: Prisma.PenaltyScalarWhereInput | Prisma.PenaltyScalarWhereInput[]
  id?: Prisma.StringFilter<"Penalty"> | string
  memberId?: Prisma.StringFilter<"Penalty"> | string
  loanId?: Prisma.StringNullableFilter<"Penalty"> | string | null
  shortLoanId?: Prisma.StringNullableFilter<"Penalty"> | string | null
  penaltyAmount?: Prisma.FloatFilter<"Penalty"> | number
  status?: Prisma.EnumTransactionStatusFilter<"Penalty"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"Penalty"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Penalty"> | Date | string
}

export type PenaltyCreateWithoutSavingsInput = {
  id?: string
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutPenaltiesInput
  loan?: Prisma.LoanCreateNestedOneWithoutPenaltiesInput
  shortLoan?: Prisma.ShortLoanCreateNestedOneWithoutPenaltiesInput
}

export type PenaltyUncheckedCreateWithoutSavingsInput = {
  id?: string
  memberId: string
  loanId?: string | null
  shortLoanId?: string | null
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PenaltyCreateOrConnectWithoutSavingsInput = {
  where: Prisma.PenaltyWhereUniqueInput
  create: Prisma.XOR<Prisma.PenaltyCreateWithoutSavingsInput, Prisma.PenaltyUncheckedCreateWithoutSavingsInput>
}

export type PenaltyUpsertWithoutSavingsInput = {
  update: Prisma.XOR<Prisma.PenaltyUpdateWithoutSavingsInput, Prisma.PenaltyUncheckedUpdateWithoutSavingsInput>
  create: Prisma.XOR<Prisma.PenaltyCreateWithoutSavingsInput, Prisma.PenaltyUncheckedCreateWithoutSavingsInput>
  where?: Prisma.PenaltyWhereInput
}

export type PenaltyUpdateToOneWithWhereWithoutSavingsInput = {
  where?: Prisma.PenaltyWhereInput
  data: Prisma.XOR<Prisma.PenaltyUpdateWithoutSavingsInput, Prisma.PenaltyUncheckedUpdateWithoutSavingsInput>
}

export type PenaltyUpdateWithoutSavingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutPenaltiesNestedInput
  loan?: Prisma.LoanUpdateOneWithoutPenaltiesNestedInput
  shortLoan?: Prisma.ShortLoanUpdateOneWithoutPenaltiesNestedInput
}

export type PenaltyUncheckedUpdateWithoutSavingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PenaltyCreateWithoutLoanInput = {
  id?: string
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutPenaltiesInput
  shortLoan?: Prisma.ShortLoanCreateNestedOneWithoutPenaltiesInput
  savings?: Prisma.SavingCreateNestedManyWithoutPenaltyInput
}

export type PenaltyUncheckedCreateWithoutLoanInput = {
  id?: string
  memberId: string
  shortLoanId?: string | null
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  savings?: Prisma.SavingUncheckedCreateNestedManyWithoutPenaltyInput
}

export type PenaltyCreateOrConnectWithoutLoanInput = {
  where: Prisma.PenaltyWhereUniqueInput
  create: Prisma.XOR<Prisma.PenaltyCreateWithoutLoanInput, Prisma.PenaltyUncheckedCreateWithoutLoanInput>
}

export type PenaltyCreateManyLoanInputEnvelope = {
  data: Prisma.PenaltyCreateManyLoanInput | Prisma.PenaltyCreateManyLoanInput[]
  skipDuplicates?: boolean
}

export type PenaltyUpsertWithWhereUniqueWithoutLoanInput = {
  where: Prisma.PenaltyWhereUniqueInput
  update: Prisma.XOR<Prisma.PenaltyUpdateWithoutLoanInput, Prisma.PenaltyUncheckedUpdateWithoutLoanInput>
  create: Prisma.XOR<Prisma.PenaltyCreateWithoutLoanInput, Prisma.PenaltyUncheckedCreateWithoutLoanInput>
}

export type PenaltyUpdateWithWhereUniqueWithoutLoanInput = {
  where: Prisma.PenaltyWhereUniqueInput
  data: Prisma.XOR<Prisma.PenaltyUpdateWithoutLoanInput, Prisma.PenaltyUncheckedUpdateWithoutLoanInput>
}

export type PenaltyUpdateManyWithWhereWithoutLoanInput = {
  where: Prisma.PenaltyScalarWhereInput
  data: Prisma.XOR<Prisma.PenaltyUpdateManyMutationInput, Prisma.PenaltyUncheckedUpdateManyWithoutLoanInput>
}

export type PenaltyCreateWithoutShortLoanInput = {
  id?: string
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutPenaltiesInput
  loan?: Prisma.LoanCreateNestedOneWithoutPenaltiesInput
  savings?: Prisma.SavingCreateNestedManyWithoutPenaltyInput
}

export type PenaltyUncheckedCreateWithoutShortLoanInput = {
  id?: string
  memberId: string
  loanId?: string | null
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  savings?: Prisma.SavingUncheckedCreateNestedManyWithoutPenaltyInput
}

export type PenaltyCreateOrConnectWithoutShortLoanInput = {
  where: Prisma.PenaltyWhereUniqueInput
  create: Prisma.XOR<Prisma.PenaltyCreateWithoutShortLoanInput, Prisma.PenaltyUncheckedCreateWithoutShortLoanInput>
}

export type PenaltyCreateManyShortLoanInputEnvelope = {
  data: Prisma.PenaltyCreateManyShortLoanInput | Prisma.PenaltyCreateManyShortLoanInput[]
  skipDuplicates?: boolean
}

export type PenaltyUpsertWithWhereUniqueWithoutShortLoanInput = {
  where: Prisma.PenaltyWhereUniqueInput
  update: Prisma.XOR<Prisma.PenaltyUpdateWithoutShortLoanInput, Prisma.PenaltyUncheckedUpdateWithoutShortLoanInput>
  create: Prisma.XOR<Prisma.PenaltyCreateWithoutShortLoanInput, Prisma.PenaltyUncheckedCreateWithoutShortLoanInput>
}

export type PenaltyUpdateWithWhereUniqueWithoutShortLoanInput = {
  where: Prisma.PenaltyWhereUniqueInput
  data: Prisma.XOR<Prisma.PenaltyUpdateWithoutShortLoanInput, Prisma.PenaltyUncheckedUpdateWithoutShortLoanInput>
}

export type PenaltyUpdateManyWithWhereWithoutShortLoanInput = {
  where: Prisma.PenaltyScalarWhereInput
  data: Prisma.XOR<Prisma.PenaltyUpdateManyMutationInput, Prisma.PenaltyUncheckedUpdateManyWithoutShortLoanInput>
}

export type PenaltyCreateManyMemberInput = {
  id?: string
  loanId?: string | null
  shortLoanId?: string | null
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PenaltyUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  loan?: Prisma.LoanUpdateOneWithoutPenaltiesNestedInput
  shortLoan?: Prisma.ShortLoanUpdateOneWithoutPenaltiesNestedInput
  savings?: Prisma.SavingUpdateManyWithoutPenaltyNestedInput
}

export type PenaltyUncheckedUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  savings?: Prisma.SavingUncheckedUpdateManyWithoutPenaltyNestedInput
}

export type PenaltyUncheckedUpdateManyWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PenaltyCreateManyLoanInput = {
  id?: string
  memberId: string
  shortLoanId?: string | null
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PenaltyUpdateWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutPenaltiesNestedInput
  shortLoan?: Prisma.ShortLoanUpdateOneWithoutPenaltiesNestedInput
  savings?: Prisma.SavingUpdateManyWithoutPenaltyNestedInput
}

export type PenaltyUncheckedUpdateWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  savings?: Prisma.SavingUncheckedUpdateManyWithoutPenaltyNestedInput
}

export type PenaltyUncheckedUpdateManyWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PenaltyCreateManyShortLoanInput = {
  id?: string
  memberId: string
  loanId?: string | null
  penaltyAmount?: number
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PenaltyUpdateWithoutShortLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutPenaltiesNestedInput
  loan?: Prisma.LoanUpdateOneWithoutPenaltiesNestedInput
  savings?: Prisma.SavingUpdateManyWithoutPenaltyNestedInput
}

export type PenaltyUncheckedUpdateWithoutShortLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  savings?: Prisma.SavingUncheckedUpdateManyWithoutPenaltyNestedInput
}

export type PenaltyUncheckedUpdateManyWithoutShortLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PenaltyCountOutputType
 */

export type PenaltyCountOutputType = {
  savings: number
}

export type PenaltyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  savings?: boolean | PenaltyCountOutputTypeCountSavingsArgs
}

/**
 * PenaltyCountOutputType without action
 */
export type PenaltyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenaltyCountOutputType
   */
  select?: Prisma.PenaltyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PenaltyCountOutputType without action
 */
export type PenaltyCountOutputTypeCountSavingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SavingWhereInput
}


export type PenaltySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  loanId?: boolean
  shortLoanId?: boolean
  penaltyAmount?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Penalty$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Penalty$shortLoanArgs<ExtArgs>
  savings?: boolean | Prisma.Penalty$savingsArgs<ExtArgs>
  _count?: boolean | Prisma.PenaltyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["penalty"]>

export type PenaltySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  loanId?: boolean
  shortLoanId?: boolean
  penaltyAmount?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Penalty$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Penalty$shortLoanArgs<ExtArgs>
}, ExtArgs["result"]["penalty"]>

export type PenaltySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  loanId?: boolean
  shortLoanId?: boolean
  penaltyAmount?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Penalty$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Penalty$shortLoanArgs<ExtArgs>
}, ExtArgs["result"]["penalty"]>

export type PenaltySelectScalar = {
  id?: boolean
  memberId?: boolean
  loanId?: boolean
  shortLoanId?: boolean
  penaltyAmount?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PenaltyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "memberId" | "loanId" | "shortLoanId" | "penaltyAmount" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["penalty"]>
export type PenaltyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Penalty$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Penalty$shortLoanArgs<ExtArgs>
  savings?: boolean | Prisma.Penalty$savingsArgs<ExtArgs>
  _count?: boolean | Prisma.PenaltyCountOutputTypeDefaultArgs<ExtArgs>
}
export type PenaltyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Penalty$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Penalty$shortLoanArgs<ExtArgs>
}
export type PenaltyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Penalty$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Penalty$shortLoanArgs<ExtArgs>
}

export type $PenaltyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Penalty"
  objects: {
    member: Prisma.$MemberPayload<ExtArgs>
    loan: Prisma.$LoanPayload<ExtArgs> | null
    shortLoan: Prisma.$ShortLoanPayload<ExtArgs> | null
    savings: Prisma.$SavingPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    memberId: string
    loanId: string | null
    shortLoanId: string | null
    penaltyAmount: number
    status: $Enums.TransactionStatus
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["penalty"]>
  composites: {}
}

export type PenaltyGetPayload<S extends boolean | null | undefined | PenaltyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PenaltyPayload, S>

export type PenaltyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PenaltyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PenaltyCountAggregateInputType | true
  }

export interface PenaltyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Penalty'], meta: { name: 'Penalty' } }
  /**
   * Find zero or one Penalty that matches the filter.
   * @param {PenaltyFindUniqueArgs} args - Arguments to find a Penalty
   * @example
   * // Get one Penalty
   * const penalty = await prisma.penalty.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PenaltyFindUniqueArgs>(args: Prisma.SelectSubset<T, PenaltyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PenaltyClient<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Penalty that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PenaltyFindUniqueOrThrowArgs} args - Arguments to find a Penalty
   * @example
   * // Get one Penalty
   * const penalty = await prisma.penalty.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PenaltyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PenaltyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PenaltyClient<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Penalty that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenaltyFindFirstArgs} args - Arguments to find a Penalty
   * @example
   * // Get one Penalty
   * const penalty = await prisma.penalty.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PenaltyFindFirstArgs>(args?: Prisma.SelectSubset<T, PenaltyFindFirstArgs<ExtArgs>>): Prisma.Prisma__PenaltyClient<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Penalty that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenaltyFindFirstOrThrowArgs} args - Arguments to find a Penalty
   * @example
   * // Get one Penalty
   * const penalty = await prisma.penalty.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PenaltyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PenaltyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PenaltyClient<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Penalties that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenaltyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Penalties
   * const penalties = await prisma.penalty.findMany()
   * 
   * // Get first 10 Penalties
   * const penalties = await prisma.penalty.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const penaltyWithIdOnly = await prisma.penalty.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PenaltyFindManyArgs>(args?: Prisma.SelectSubset<T, PenaltyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Penalty.
   * @param {PenaltyCreateArgs} args - Arguments to create a Penalty.
   * @example
   * // Create one Penalty
   * const Penalty = await prisma.penalty.create({
   *   data: {
   *     // ... data to create a Penalty
   *   }
   * })
   * 
   */
  create<T extends PenaltyCreateArgs>(args: Prisma.SelectSubset<T, PenaltyCreateArgs<ExtArgs>>): Prisma.Prisma__PenaltyClient<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Penalties.
   * @param {PenaltyCreateManyArgs} args - Arguments to create many Penalties.
   * @example
   * // Create many Penalties
   * const penalty = await prisma.penalty.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PenaltyCreateManyArgs>(args?: Prisma.SelectSubset<T, PenaltyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Penalties and returns the data saved in the database.
   * @param {PenaltyCreateManyAndReturnArgs} args - Arguments to create many Penalties.
   * @example
   * // Create many Penalties
   * const penalty = await prisma.penalty.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Penalties and only return the `id`
   * const penaltyWithIdOnly = await prisma.penalty.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PenaltyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PenaltyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Penalty.
   * @param {PenaltyDeleteArgs} args - Arguments to delete one Penalty.
   * @example
   * // Delete one Penalty
   * const Penalty = await prisma.penalty.delete({
   *   where: {
   *     // ... filter to delete one Penalty
   *   }
   * })
   * 
   */
  delete<T extends PenaltyDeleteArgs>(args: Prisma.SelectSubset<T, PenaltyDeleteArgs<ExtArgs>>): Prisma.Prisma__PenaltyClient<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Penalty.
   * @param {PenaltyUpdateArgs} args - Arguments to update one Penalty.
   * @example
   * // Update one Penalty
   * const penalty = await prisma.penalty.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PenaltyUpdateArgs>(args: Prisma.SelectSubset<T, PenaltyUpdateArgs<ExtArgs>>): Prisma.Prisma__PenaltyClient<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Penalties.
   * @param {PenaltyDeleteManyArgs} args - Arguments to filter Penalties to delete.
   * @example
   * // Delete a few Penalties
   * const { count } = await prisma.penalty.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PenaltyDeleteManyArgs>(args?: Prisma.SelectSubset<T, PenaltyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Penalties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenaltyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Penalties
   * const penalty = await prisma.penalty.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PenaltyUpdateManyArgs>(args: Prisma.SelectSubset<T, PenaltyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Penalties and returns the data updated in the database.
   * @param {PenaltyUpdateManyAndReturnArgs} args - Arguments to update many Penalties.
   * @example
   * // Update many Penalties
   * const penalty = await prisma.penalty.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Penalties and only return the `id`
   * const penaltyWithIdOnly = await prisma.penalty.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PenaltyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PenaltyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Penalty.
   * @param {PenaltyUpsertArgs} args - Arguments to update or create a Penalty.
   * @example
   * // Update or create a Penalty
   * const penalty = await prisma.penalty.upsert({
   *   create: {
   *     // ... data to create a Penalty
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Penalty we want to update
   *   }
   * })
   */
  upsert<T extends PenaltyUpsertArgs>(args: Prisma.SelectSubset<T, PenaltyUpsertArgs<ExtArgs>>): Prisma.Prisma__PenaltyClient<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Penalties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenaltyCountArgs} args - Arguments to filter Penalties to count.
   * @example
   * // Count the number of Penalties
   * const count = await prisma.penalty.count({
   *   where: {
   *     // ... the filter for the Penalties we want to count
   *   }
   * })
  **/
  count<T extends PenaltyCountArgs>(
    args?: Prisma.Subset<T, PenaltyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PenaltyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Penalty.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenaltyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PenaltyAggregateArgs>(args: Prisma.Subset<T, PenaltyAggregateArgs>): Prisma.PrismaPromise<GetPenaltyAggregateType<T>>

  /**
   * Group by Penalty.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenaltyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PenaltyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PenaltyGroupByArgs['orderBy'] }
      : { orderBy?: PenaltyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PenaltyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPenaltyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Penalty model
 */
readonly fields: PenaltyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Penalty.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PenaltyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  member<T extends Prisma.MemberDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MemberDefaultArgs<ExtArgs>>): Prisma.Prisma__MemberClient<runtime.Types.Result.GetResult<Prisma.$MemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  loan<T extends Prisma.Penalty$loanArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Penalty$loanArgs<ExtArgs>>): Prisma.Prisma__LoanClient<runtime.Types.Result.GetResult<Prisma.$LoanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  shortLoan<T extends Prisma.Penalty$shortLoanArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Penalty$shortLoanArgs<ExtArgs>>): Prisma.Prisma__ShortLoanClient<runtime.Types.Result.GetResult<Prisma.$ShortLoanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  savings<T extends Prisma.Penalty$savingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Penalty$savingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Penalty model
 */
export interface PenaltyFieldRefs {
  readonly id: Prisma.FieldRef<"Penalty", 'String'>
  readonly memberId: Prisma.FieldRef<"Penalty", 'String'>
  readonly loanId: Prisma.FieldRef<"Penalty", 'String'>
  readonly shortLoanId: Prisma.FieldRef<"Penalty", 'String'>
  readonly penaltyAmount: Prisma.FieldRef<"Penalty", 'Float'>
  readonly status: Prisma.FieldRef<"Penalty", 'TransactionStatus'>
  readonly createdAt: Prisma.FieldRef<"Penalty", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Penalty", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Penalty findUnique
 */
export type PenaltyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
  /**
   * Filter, which Penalty to fetch.
   */
  where: Prisma.PenaltyWhereUniqueInput
}

/**
 * Penalty findUniqueOrThrow
 */
export type PenaltyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
  /**
   * Filter, which Penalty to fetch.
   */
  where: Prisma.PenaltyWhereUniqueInput
}

/**
 * Penalty findFirst
 */
export type PenaltyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
  /**
   * Filter, which Penalty to fetch.
   */
  where?: Prisma.PenaltyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Penalties to fetch.
   */
  orderBy?: Prisma.PenaltyOrderByWithRelationInput | Prisma.PenaltyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Penalties.
   */
  cursor?: Prisma.PenaltyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Penalties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Penalties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Penalties.
   */
  distinct?: Prisma.PenaltyScalarFieldEnum | Prisma.PenaltyScalarFieldEnum[]
}

/**
 * Penalty findFirstOrThrow
 */
export type PenaltyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
  /**
   * Filter, which Penalty to fetch.
   */
  where?: Prisma.PenaltyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Penalties to fetch.
   */
  orderBy?: Prisma.PenaltyOrderByWithRelationInput | Prisma.PenaltyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Penalties.
   */
  cursor?: Prisma.PenaltyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Penalties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Penalties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Penalties.
   */
  distinct?: Prisma.PenaltyScalarFieldEnum | Prisma.PenaltyScalarFieldEnum[]
}

/**
 * Penalty findMany
 */
export type PenaltyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
  /**
   * Filter, which Penalties to fetch.
   */
  where?: Prisma.PenaltyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Penalties to fetch.
   */
  orderBy?: Prisma.PenaltyOrderByWithRelationInput | Prisma.PenaltyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Penalties.
   */
  cursor?: Prisma.PenaltyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Penalties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Penalties.
   */
  skip?: number
  distinct?: Prisma.PenaltyScalarFieldEnum | Prisma.PenaltyScalarFieldEnum[]
}

/**
 * Penalty create
 */
export type PenaltyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
  /**
   * The data needed to create a Penalty.
   */
  data: Prisma.XOR<Prisma.PenaltyCreateInput, Prisma.PenaltyUncheckedCreateInput>
}

/**
 * Penalty createMany
 */
export type PenaltyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Penalties.
   */
  data: Prisma.PenaltyCreateManyInput | Prisma.PenaltyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Penalty createManyAndReturn
 */
export type PenaltyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * The data used to create many Penalties.
   */
  data: Prisma.PenaltyCreateManyInput | Prisma.PenaltyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Penalty update
 */
export type PenaltyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
  /**
   * The data needed to update a Penalty.
   */
  data: Prisma.XOR<Prisma.PenaltyUpdateInput, Prisma.PenaltyUncheckedUpdateInput>
  /**
   * Choose, which Penalty to update.
   */
  where: Prisma.PenaltyWhereUniqueInput
}

/**
 * Penalty updateMany
 */
export type PenaltyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Penalties.
   */
  data: Prisma.XOR<Prisma.PenaltyUpdateManyMutationInput, Prisma.PenaltyUncheckedUpdateManyInput>
  /**
   * Filter which Penalties to update
   */
  where?: Prisma.PenaltyWhereInput
  /**
   * Limit how many Penalties to update.
   */
  limit?: number
}

/**
 * Penalty updateManyAndReturn
 */
export type PenaltyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * The data used to update Penalties.
   */
  data: Prisma.XOR<Prisma.PenaltyUpdateManyMutationInput, Prisma.PenaltyUncheckedUpdateManyInput>
  /**
   * Filter which Penalties to update
   */
  where?: Prisma.PenaltyWhereInput
  /**
   * Limit how many Penalties to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Penalty upsert
 */
export type PenaltyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
  /**
   * The filter to search for the Penalty to update in case it exists.
   */
  where: Prisma.PenaltyWhereUniqueInput
  /**
   * In case the Penalty found by the `where` argument doesn't exist, create a new Penalty with this data.
   */
  create: Prisma.XOR<Prisma.PenaltyCreateInput, Prisma.PenaltyUncheckedCreateInput>
  /**
   * In case the Penalty was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PenaltyUpdateInput, Prisma.PenaltyUncheckedUpdateInput>
}

/**
 * Penalty delete
 */
export type PenaltyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
  /**
   * Filter which Penalty to delete.
   */
  where: Prisma.PenaltyWhereUniqueInput
}

/**
 * Penalty deleteMany
 */
export type PenaltyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Penalties to delete
   */
  where?: Prisma.PenaltyWhereInput
  /**
   * Limit how many Penalties to delete.
   */
  limit?: number
}

/**
 * Penalty.loan
 */
export type Penalty$loanArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Loan
   */
  select?: Prisma.LoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Loan
   */
  omit?: Prisma.LoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanInclude<ExtArgs> | null
  where?: Prisma.LoanWhereInput
}

/**
 * Penalty.shortLoan
 */
export type Penalty$shortLoanArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShortLoan
   */
  select?: Prisma.ShortLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShortLoan
   */
  omit?: Prisma.ShortLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortLoanInclude<ExtArgs> | null
  where?: Prisma.ShortLoanWhereInput
}

/**
 * Penalty.savings
 */
export type Penalty$savingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingInclude<ExtArgs> | null
  where?: Prisma.SavingWhereInput
  orderBy?: Prisma.SavingOrderByWithRelationInput | Prisma.SavingOrderByWithRelationInput[]
  cursor?: Prisma.SavingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SavingScalarFieldEnum | Prisma.SavingScalarFieldEnum[]
}

/**
 * Penalty without action
 */
export type PenaltyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
}
