
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Saving` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Saving
 * 
 */
export type SavingModel = runtime.Types.Result.DefaultSelection<Prisma.$SavingPayload>

export type AggregateSaving = {
  _count: SavingCountAggregateOutputType | null
  _avg: SavingAvgAggregateOutputType | null
  _sum: SavingSumAggregateOutputType | null
  _min: SavingMinAggregateOutputType | null
  _max: SavingMaxAggregateOutputType | null
}

export type SavingAvgAggregateOutputType = {
  amount: number | null
}

export type SavingSumAggregateOutputType = {
  amount: number | null
}

export type SavingMinAggregateOutputType = {
  id: string | null
  amount: number | null
  mPesaRef: string | null
  authorizedBy: string | null
  loanId: string | null
  shortLoanId: string | null
  penaltyId: string | null
  memberId: string | null
  status: $Enums.TransactionStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SavingMaxAggregateOutputType = {
  id: string | null
  amount: number | null
  mPesaRef: string | null
  authorizedBy: string | null
  loanId: string | null
  shortLoanId: string | null
  penaltyId: string | null
  memberId: string | null
  status: $Enums.TransactionStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SavingCountAggregateOutputType = {
  id: number
  amount: number
  mPesaRef: number
  authorizedBy: number
  loanId: number
  shortLoanId: number
  penaltyId: number
  memberId: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SavingAvgAggregateInputType = {
  amount?: true
}

export type SavingSumAggregateInputType = {
  amount?: true
}

export type SavingMinAggregateInputType = {
  id?: true
  amount?: true
  mPesaRef?: true
  authorizedBy?: true
  loanId?: true
  shortLoanId?: true
  penaltyId?: true
  memberId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type SavingMaxAggregateInputType = {
  id?: true
  amount?: true
  mPesaRef?: true
  authorizedBy?: true
  loanId?: true
  shortLoanId?: true
  penaltyId?: true
  memberId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type SavingCountAggregateInputType = {
  id?: true
  amount?: true
  mPesaRef?: true
  authorizedBy?: true
  loanId?: true
  shortLoanId?: true
  penaltyId?: true
  memberId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SavingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Saving to aggregate.
   */
  where?: Prisma.SavingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Savings to fetch.
   */
  orderBy?: Prisma.SavingOrderByWithRelationInput | Prisma.SavingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SavingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Savings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Savings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Savings
  **/
  _count?: true | SavingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SavingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SavingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SavingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SavingMaxAggregateInputType
}

export type GetSavingAggregateType<T extends SavingAggregateArgs> = {
      [P in keyof T & keyof AggregateSaving]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSaving[P]>
    : Prisma.GetScalarType<T[P], AggregateSaving[P]>
}




export type SavingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SavingWhereInput
  orderBy?: Prisma.SavingOrderByWithAggregationInput | Prisma.SavingOrderByWithAggregationInput[]
  by: Prisma.SavingScalarFieldEnum[] | Prisma.SavingScalarFieldEnum
  having?: Prisma.SavingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SavingCountAggregateInputType | true
  _avg?: SavingAvgAggregateInputType
  _sum?: SavingSumAggregateInputType
  _min?: SavingMinAggregateInputType
  _max?: SavingMaxAggregateInputType
}

export type SavingGroupByOutputType = {
  id: string
  amount: number
  mPesaRef: string | null
  authorizedBy: string | null
  loanId: string | null
  shortLoanId: string | null
  penaltyId: string | null
  memberId: string
  status: $Enums.TransactionStatus
  createdAt: Date
  updatedAt: Date
  _count: SavingCountAggregateOutputType | null
  _avg: SavingAvgAggregateOutputType | null
  _sum: SavingSumAggregateOutputType | null
  _min: SavingMinAggregateOutputType | null
  _max: SavingMaxAggregateOutputType | null
}

type GetSavingGroupByPayload<T extends SavingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SavingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SavingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SavingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SavingGroupByOutputType[P]>
      }
    >
  >



export type SavingWhereInput = {
  AND?: Prisma.SavingWhereInput | Prisma.SavingWhereInput[]
  OR?: Prisma.SavingWhereInput[]
  NOT?: Prisma.SavingWhereInput | Prisma.SavingWhereInput[]
  id?: Prisma.StringFilter<"Saving"> | string
  amount?: Prisma.FloatFilter<"Saving"> | number
  mPesaRef?: Prisma.StringNullableFilter<"Saving"> | string | null
  authorizedBy?: Prisma.StringNullableFilter<"Saving"> | string | null
  loanId?: Prisma.StringNullableFilter<"Saving"> | string | null
  shortLoanId?: Prisma.StringNullableFilter<"Saving"> | string | null
  penaltyId?: Prisma.StringNullableFilter<"Saving"> | string | null
  memberId?: Prisma.StringFilter<"Saving"> | string
  status?: Prisma.EnumTransactionStatusFilter<"Saving"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"Saving"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Saving"> | Date | string
  member?: Prisma.XOR<Prisma.MemberScalarRelationFilter, Prisma.MemberWhereInput>
  loan?: Prisma.XOR<Prisma.LoanNullableScalarRelationFilter, Prisma.LoanWhereInput> | null
  shortLoan?: Prisma.XOR<Prisma.ShortLoanNullableScalarRelationFilter, Prisma.ShortLoanWhereInput> | null
  penalty?: Prisma.XOR<Prisma.PenaltyNullableScalarRelationFilter, Prisma.PenaltyWhereInput> | null
  deduction?: Prisma.XOR<Prisma.DeductionNullableScalarRelationFilter, Prisma.DeductionWhereInput> | null
}

export type SavingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  mPesaRef?: Prisma.SortOrderInput | Prisma.SortOrder
  authorizedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  loanId?: Prisma.SortOrderInput | Prisma.SortOrder
  shortLoanId?: Prisma.SortOrderInput | Prisma.SortOrder
  penaltyId?: Prisma.SortOrderInput | Prisma.SortOrder
  memberId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  member?: Prisma.MemberOrderByWithRelationInput
  loan?: Prisma.LoanOrderByWithRelationInput
  shortLoan?: Prisma.ShortLoanOrderByWithRelationInput
  penalty?: Prisma.PenaltyOrderByWithRelationInput
  deduction?: Prisma.DeductionOrderByWithRelationInput
}

export type SavingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SavingWhereInput | Prisma.SavingWhereInput[]
  OR?: Prisma.SavingWhereInput[]
  NOT?: Prisma.SavingWhereInput | Prisma.SavingWhereInput[]
  amount?: Prisma.FloatFilter<"Saving"> | number
  mPesaRef?: Prisma.StringNullableFilter<"Saving"> | string | null
  authorizedBy?: Prisma.StringNullableFilter<"Saving"> | string | null
  loanId?: Prisma.StringNullableFilter<"Saving"> | string | null
  shortLoanId?: Prisma.StringNullableFilter<"Saving"> | string | null
  penaltyId?: Prisma.StringNullableFilter<"Saving"> | string | null
  memberId?: Prisma.StringFilter<"Saving"> | string
  status?: Prisma.EnumTransactionStatusFilter<"Saving"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"Saving"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Saving"> | Date | string
  member?: Prisma.XOR<Prisma.MemberScalarRelationFilter, Prisma.MemberWhereInput>
  loan?: Prisma.XOR<Prisma.LoanNullableScalarRelationFilter, Prisma.LoanWhereInput> | null
  shortLoan?: Prisma.XOR<Prisma.ShortLoanNullableScalarRelationFilter, Prisma.ShortLoanWhereInput> | null
  penalty?: Prisma.XOR<Prisma.PenaltyNullableScalarRelationFilter, Prisma.PenaltyWhereInput> | null
  deduction?: Prisma.XOR<Prisma.DeductionNullableScalarRelationFilter, Prisma.DeductionWhereInput> | null
}, "id">

export type SavingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  mPesaRef?: Prisma.SortOrderInput | Prisma.SortOrder
  authorizedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  loanId?: Prisma.SortOrderInput | Prisma.SortOrder
  shortLoanId?: Prisma.SortOrderInput | Prisma.SortOrder
  penaltyId?: Prisma.SortOrderInput | Prisma.SortOrder
  memberId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SavingCountOrderByAggregateInput
  _avg?: Prisma.SavingAvgOrderByAggregateInput
  _max?: Prisma.SavingMaxOrderByAggregateInput
  _min?: Prisma.SavingMinOrderByAggregateInput
  _sum?: Prisma.SavingSumOrderByAggregateInput
}

export type SavingScalarWhereWithAggregatesInput = {
  AND?: Prisma.SavingScalarWhereWithAggregatesInput | Prisma.SavingScalarWhereWithAggregatesInput[]
  OR?: Prisma.SavingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SavingScalarWhereWithAggregatesInput | Prisma.SavingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Saving"> | string
  amount?: Prisma.FloatWithAggregatesFilter<"Saving"> | number
  mPesaRef?: Prisma.StringNullableWithAggregatesFilter<"Saving"> | string | null
  authorizedBy?: Prisma.StringNullableWithAggregatesFilter<"Saving"> | string | null
  loanId?: Prisma.StringNullableWithAggregatesFilter<"Saving"> | string | null
  shortLoanId?: Prisma.StringNullableWithAggregatesFilter<"Saving"> | string | null
  penaltyId?: Prisma.StringNullableWithAggregatesFilter<"Saving"> | string | null
  memberId?: Prisma.StringWithAggregatesFilter<"Saving"> | string
  status?: Prisma.EnumTransactionStatusWithAggregatesFilter<"Saving"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Saving"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Saving"> | Date | string
}

export type SavingCreateInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutSavingsInput
  loan?: Prisma.LoanCreateNestedOneWithoutSavingsInput
  shortLoan?: Prisma.ShortLoanCreateNestedOneWithoutSavingsInput
  penalty?: Prisma.PenaltyCreateNestedOneWithoutSavingsInput
  deduction?: Prisma.DeductionCreateNestedOneWithoutSavingInput
}

export type SavingUncheckedCreateInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  loanId?: string | null
  shortLoanId?: string | null
  penaltyId?: string | null
  memberId: string
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  deduction?: Prisma.DeductionUncheckedCreateNestedOneWithoutSavingInput
}

export type SavingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutSavingsNestedInput
  loan?: Prisma.LoanUpdateOneWithoutSavingsNestedInput
  shortLoan?: Prisma.ShortLoanUpdateOneWithoutSavingsNestedInput
  penalty?: Prisma.PenaltyUpdateOneWithoutSavingsNestedInput
  deduction?: Prisma.DeductionUpdateOneWithoutSavingNestedInput
}

export type SavingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deduction?: Prisma.DeductionUncheckedUpdateOneWithoutSavingNestedInput
}

export type SavingCreateManyInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  loanId?: string | null
  shortLoanId?: string | null
  penaltyId?: string | null
  memberId: string
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SavingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavingListRelationFilter = {
  every?: Prisma.SavingWhereInput
  some?: Prisma.SavingWhereInput
  none?: Prisma.SavingWhereInput
}

export type SavingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SavingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  mPesaRef?: Prisma.SortOrder
  authorizedBy?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  shortLoanId?: Prisma.SortOrder
  penaltyId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SavingAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type SavingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  mPesaRef?: Prisma.SortOrder
  authorizedBy?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  shortLoanId?: Prisma.SortOrder
  penaltyId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SavingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  mPesaRef?: Prisma.SortOrder
  authorizedBy?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  shortLoanId?: Prisma.SortOrder
  penaltyId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SavingSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type SavingScalarRelationFilter = {
  is?: Prisma.SavingWhereInput
  isNot?: Prisma.SavingWhereInput
}

export type SavingCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutMemberInput, Prisma.SavingUncheckedCreateWithoutMemberInput> | Prisma.SavingCreateWithoutMemberInput[] | Prisma.SavingUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutMemberInput | Prisma.SavingCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.SavingCreateManyMemberInputEnvelope
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
}

export type SavingUncheckedCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutMemberInput, Prisma.SavingUncheckedCreateWithoutMemberInput> | Prisma.SavingCreateWithoutMemberInput[] | Prisma.SavingUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutMemberInput | Prisma.SavingCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.SavingCreateManyMemberInputEnvelope
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
}

export type SavingUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutMemberInput, Prisma.SavingUncheckedCreateWithoutMemberInput> | Prisma.SavingCreateWithoutMemberInput[] | Prisma.SavingUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutMemberInput | Prisma.SavingCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.SavingUpsertWithWhereUniqueWithoutMemberInput | Prisma.SavingUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.SavingCreateManyMemberInputEnvelope
  set?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  disconnect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  delete?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  update?: Prisma.SavingUpdateWithWhereUniqueWithoutMemberInput | Prisma.SavingUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.SavingUpdateManyWithWhereWithoutMemberInput | Prisma.SavingUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.SavingScalarWhereInput | Prisma.SavingScalarWhereInput[]
}

export type SavingUncheckedUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutMemberInput, Prisma.SavingUncheckedCreateWithoutMemberInput> | Prisma.SavingCreateWithoutMemberInput[] | Prisma.SavingUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutMemberInput | Prisma.SavingCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.SavingUpsertWithWhereUniqueWithoutMemberInput | Prisma.SavingUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.SavingCreateManyMemberInputEnvelope
  set?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  disconnect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  delete?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  update?: Prisma.SavingUpdateWithWhereUniqueWithoutMemberInput | Prisma.SavingUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.SavingUpdateManyWithWhereWithoutMemberInput | Prisma.SavingUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.SavingScalarWhereInput | Prisma.SavingScalarWhereInput[]
}

export type EnumTransactionStatusFieldUpdateOperationsInput = {
  set?: $Enums.TransactionStatus
}

export type SavingCreateNestedOneWithoutDeductionInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutDeductionInput, Prisma.SavingUncheckedCreateWithoutDeductionInput>
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutDeductionInput
  connect?: Prisma.SavingWhereUniqueInput
}

export type SavingUpdateOneRequiredWithoutDeductionNestedInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutDeductionInput, Prisma.SavingUncheckedCreateWithoutDeductionInput>
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutDeductionInput
  upsert?: Prisma.SavingUpsertWithoutDeductionInput
  connect?: Prisma.SavingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SavingUpdateToOneWithWhereWithoutDeductionInput, Prisma.SavingUpdateWithoutDeductionInput>, Prisma.SavingUncheckedUpdateWithoutDeductionInput>
}

export type SavingCreateNestedManyWithoutLoanInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutLoanInput, Prisma.SavingUncheckedCreateWithoutLoanInput> | Prisma.SavingCreateWithoutLoanInput[] | Prisma.SavingUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutLoanInput | Prisma.SavingCreateOrConnectWithoutLoanInput[]
  createMany?: Prisma.SavingCreateManyLoanInputEnvelope
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
}

export type SavingUncheckedCreateNestedManyWithoutLoanInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutLoanInput, Prisma.SavingUncheckedCreateWithoutLoanInput> | Prisma.SavingCreateWithoutLoanInput[] | Prisma.SavingUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutLoanInput | Prisma.SavingCreateOrConnectWithoutLoanInput[]
  createMany?: Prisma.SavingCreateManyLoanInputEnvelope
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
}

export type SavingUpdateManyWithoutLoanNestedInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutLoanInput, Prisma.SavingUncheckedCreateWithoutLoanInput> | Prisma.SavingCreateWithoutLoanInput[] | Prisma.SavingUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutLoanInput | Prisma.SavingCreateOrConnectWithoutLoanInput[]
  upsert?: Prisma.SavingUpsertWithWhereUniqueWithoutLoanInput | Prisma.SavingUpsertWithWhereUniqueWithoutLoanInput[]
  createMany?: Prisma.SavingCreateManyLoanInputEnvelope
  set?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  disconnect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  delete?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  update?: Prisma.SavingUpdateWithWhereUniqueWithoutLoanInput | Prisma.SavingUpdateWithWhereUniqueWithoutLoanInput[]
  updateMany?: Prisma.SavingUpdateManyWithWhereWithoutLoanInput | Prisma.SavingUpdateManyWithWhereWithoutLoanInput[]
  deleteMany?: Prisma.SavingScalarWhereInput | Prisma.SavingScalarWhereInput[]
}

export type SavingUncheckedUpdateManyWithoutLoanNestedInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutLoanInput, Prisma.SavingUncheckedCreateWithoutLoanInput> | Prisma.SavingCreateWithoutLoanInput[] | Prisma.SavingUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutLoanInput | Prisma.SavingCreateOrConnectWithoutLoanInput[]
  upsert?: Prisma.SavingUpsertWithWhereUniqueWithoutLoanInput | Prisma.SavingUpsertWithWhereUniqueWithoutLoanInput[]
  createMany?: Prisma.SavingCreateManyLoanInputEnvelope
  set?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  disconnect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  delete?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  update?: Prisma.SavingUpdateWithWhereUniqueWithoutLoanInput | Prisma.SavingUpdateWithWhereUniqueWithoutLoanInput[]
  updateMany?: Prisma.SavingUpdateManyWithWhereWithoutLoanInput | Prisma.SavingUpdateManyWithWhereWithoutLoanInput[]
  deleteMany?: Prisma.SavingScalarWhereInput | Prisma.SavingScalarWhereInput[]
}

export type SavingCreateNestedManyWithoutShortLoanInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutShortLoanInput, Prisma.SavingUncheckedCreateWithoutShortLoanInput> | Prisma.SavingCreateWithoutShortLoanInput[] | Prisma.SavingUncheckedCreateWithoutShortLoanInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutShortLoanInput | Prisma.SavingCreateOrConnectWithoutShortLoanInput[]
  createMany?: Prisma.SavingCreateManyShortLoanInputEnvelope
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
}

export type SavingUncheckedCreateNestedManyWithoutShortLoanInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutShortLoanInput, Prisma.SavingUncheckedCreateWithoutShortLoanInput> | Prisma.SavingCreateWithoutShortLoanInput[] | Prisma.SavingUncheckedCreateWithoutShortLoanInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutShortLoanInput | Prisma.SavingCreateOrConnectWithoutShortLoanInput[]
  createMany?: Prisma.SavingCreateManyShortLoanInputEnvelope
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
}

export type SavingUpdateManyWithoutShortLoanNestedInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutShortLoanInput, Prisma.SavingUncheckedCreateWithoutShortLoanInput> | Prisma.SavingCreateWithoutShortLoanInput[] | Prisma.SavingUncheckedCreateWithoutShortLoanInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutShortLoanInput | Prisma.SavingCreateOrConnectWithoutShortLoanInput[]
  upsert?: Prisma.SavingUpsertWithWhereUniqueWithoutShortLoanInput | Prisma.SavingUpsertWithWhereUniqueWithoutShortLoanInput[]
  createMany?: Prisma.SavingCreateManyShortLoanInputEnvelope
  set?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  disconnect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  delete?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  update?: Prisma.SavingUpdateWithWhereUniqueWithoutShortLoanInput | Prisma.SavingUpdateWithWhereUniqueWithoutShortLoanInput[]
  updateMany?: Prisma.SavingUpdateManyWithWhereWithoutShortLoanInput | Prisma.SavingUpdateManyWithWhereWithoutShortLoanInput[]
  deleteMany?: Prisma.SavingScalarWhereInput | Prisma.SavingScalarWhereInput[]
}

export type SavingUncheckedUpdateManyWithoutShortLoanNestedInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutShortLoanInput, Prisma.SavingUncheckedCreateWithoutShortLoanInput> | Prisma.SavingCreateWithoutShortLoanInput[] | Prisma.SavingUncheckedCreateWithoutShortLoanInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutShortLoanInput | Prisma.SavingCreateOrConnectWithoutShortLoanInput[]
  upsert?: Prisma.SavingUpsertWithWhereUniqueWithoutShortLoanInput | Prisma.SavingUpsertWithWhereUniqueWithoutShortLoanInput[]
  createMany?: Prisma.SavingCreateManyShortLoanInputEnvelope
  set?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  disconnect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  delete?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  update?: Prisma.SavingUpdateWithWhereUniqueWithoutShortLoanInput | Prisma.SavingUpdateWithWhereUniqueWithoutShortLoanInput[]
  updateMany?: Prisma.SavingUpdateManyWithWhereWithoutShortLoanInput | Prisma.SavingUpdateManyWithWhereWithoutShortLoanInput[]
  deleteMany?: Prisma.SavingScalarWhereInput | Prisma.SavingScalarWhereInput[]
}

export type SavingCreateNestedManyWithoutPenaltyInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutPenaltyInput, Prisma.SavingUncheckedCreateWithoutPenaltyInput> | Prisma.SavingCreateWithoutPenaltyInput[] | Prisma.SavingUncheckedCreateWithoutPenaltyInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutPenaltyInput | Prisma.SavingCreateOrConnectWithoutPenaltyInput[]
  createMany?: Prisma.SavingCreateManyPenaltyInputEnvelope
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
}

export type SavingUncheckedCreateNestedManyWithoutPenaltyInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutPenaltyInput, Prisma.SavingUncheckedCreateWithoutPenaltyInput> | Prisma.SavingCreateWithoutPenaltyInput[] | Prisma.SavingUncheckedCreateWithoutPenaltyInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutPenaltyInput | Prisma.SavingCreateOrConnectWithoutPenaltyInput[]
  createMany?: Prisma.SavingCreateManyPenaltyInputEnvelope
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
}

export type SavingUpdateManyWithoutPenaltyNestedInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutPenaltyInput, Prisma.SavingUncheckedCreateWithoutPenaltyInput> | Prisma.SavingCreateWithoutPenaltyInput[] | Prisma.SavingUncheckedCreateWithoutPenaltyInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutPenaltyInput | Prisma.SavingCreateOrConnectWithoutPenaltyInput[]
  upsert?: Prisma.SavingUpsertWithWhereUniqueWithoutPenaltyInput | Prisma.SavingUpsertWithWhereUniqueWithoutPenaltyInput[]
  createMany?: Prisma.SavingCreateManyPenaltyInputEnvelope
  set?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  disconnect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  delete?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  update?: Prisma.SavingUpdateWithWhereUniqueWithoutPenaltyInput | Prisma.SavingUpdateWithWhereUniqueWithoutPenaltyInput[]
  updateMany?: Prisma.SavingUpdateManyWithWhereWithoutPenaltyInput | Prisma.SavingUpdateManyWithWhereWithoutPenaltyInput[]
  deleteMany?: Prisma.SavingScalarWhereInput | Prisma.SavingScalarWhereInput[]
}

export type SavingUncheckedUpdateManyWithoutPenaltyNestedInput = {
  create?: Prisma.XOR<Prisma.SavingCreateWithoutPenaltyInput, Prisma.SavingUncheckedCreateWithoutPenaltyInput> | Prisma.SavingCreateWithoutPenaltyInput[] | Prisma.SavingUncheckedCreateWithoutPenaltyInput[]
  connectOrCreate?: Prisma.SavingCreateOrConnectWithoutPenaltyInput | Prisma.SavingCreateOrConnectWithoutPenaltyInput[]
  upsert?: Prisma.SavingUpsertWithWhereUniqueWithoutPenaltyInput | Prisma.SavingUpsertWithWhereUniqueWithoutPenaltyInput[]
  createMany?: Prisma.SavingCreateManyPenaltyInputEnvelope
  set?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  disconnect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  delete?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  connect?: Prisma.SavingWhereUniqueInput | Prisma.SavingWhereUniqueInput[]
  update?: Prisma.SavingUpdateWithWhereUniqueWithoutPenaltyInput | Prisma.SavingUpdateWithWhereUniqueWithoutPenaltyInput[]
  updateMany?: Prisma.SavingUpdateManyWithWhereWithoutPenaltyInput | Prisma.SavingUpdateManyWithWhereWithoutPenaltyInput[]
  deleteMany?: Prisma.SavingScalarWhereInput | Prisma.SavingScalarWhereInput[]
}

export type SavingCreateWithoutMemberInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  loan?: Prisma.LoanCreateNestedOneWithoutSavingsInput
  shortLoan?: Prisma.ShortLoanCreateNestedOneWithoutSavingsInput
  penalty?: Prisma.PenaltyCreateNestedOneWithoutSavingsInput
  deduction?: Prisma.DeductionCreateNestedOneWithoutSavingInput
}

export type SavingUncheckedCreateWithoutMemberInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  loanId?: string | null
  shortLoanId?: string | null
  penaltyId?: string | null
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  deduction?: Prisma.DeductionUncheckedCreateNestedOneWithoutSavingInput
}

export type SavingCreateOrConnectWithoutMemberInput = {
  where: Prisma.SavingWhereUniqueInput
  create: Prisma.XOR<Prisma.SavingCreateWithoutMemberInput, Prisma.SavingUncheckedCreateWithoutMemberInput>
}

export type SavingCreateManyMemberInputEnvelope = {
  data: Prisma.SavingCreateManyMemberInput | Prisma.SavingCreateManyMemberInput[]
  skipDuplicates?: boolean
}

export type SavingUpsertWithWhereUniqueWithoutMemberInput = {
  where: Prisma.SavingWhereUniqueInput
  update: Prisma.XOR<Prisma.SavingUpdateWithoutMemberInput, Prisma.SavingUncheckedUpdateWithoutMemberInput>
  create: Prisma.XOR<Prisma.SavingCreateWithoutMemberInput, Prisma.SavingUncheckedCreateWithoutMemberInput>
}

export type SavingUpdateWithWhereUniqueWithoutMemberInput = {
  where: Prisma.SavingWhereUniqueInput
  data: Prisma.XOR<Prisma.SavingUpdateWithoutMemberInput, Prisma.SavingUncheckedUpdateWithoutMemberInput>
}

export type SavingUpdateManyWithWhereWithoutMemberInput = {
  where: Prisma.SavingScalarWhereInput
  data: Prisma.XOR<Prisma.SavingUpdateManyMutationInput, Prisma.SavingUncheckedUpdateManyWithoutMemberInput>
}

export type SavingScalarWhereInput = {
  AND?: Prisma.SavingScalarWhereInput | Prisma.SavingScalarWhereInput[]
  OR?: Prisma.SavingScalarWhereInput[]
  NOT?: Prisma.SavingScalarWhereInput | Prisma.SavingScalarWhereInput[]
  id?: Prisma.StringFilter<"Saving"> | string
  amount?: Prisma.FloatFilter<"Saving"> | number
  mPesaRef?: Prisma.StringNullableFilter<"Saving"> | string | null
  authorizedBy?: Prisma.StringNullableFilter<"Saving"> | string | null
  loanId?: Prisma.StringNullableFilter<"Saving"> | string | null
  shortLoanId?: Prisma.StringNullableFilter<"Saving"> | string | null
  penaltyId?: Prisma.StringNullableFilter<"Saving"> | string | null
  memberId?: Prisma.StringFilter<"Saving"> | string
  status?: Prisma.EnumTransactionStatusFilter<"Saving"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"Saving"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Saving"> | Date | string
}

export type SavingCreateWithoutDeductionInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutSavingsInput
  loan?: Prisma.LoanCreateNestedOneWithoutSavingsInput
  shortLoan?: Prisma.ShortLoanCreateNestedOneWithoutSavingsInput
  penalty?: Prisma.PenaltyCreateNestedOneWithoutSavingsInput
}

export type SavingUncheckedCreateWithoutDeductionInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  loanId?: string | null
  shortLoanId?: string | null
  penaltyId?: string | null
  memberId: string
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SavingCreateOrConnectWithoutDeductionInput = {
  where: Prisma.SavingWhereUniqueInput
  create: Prisma.XOR<Prisma.SavingCreateWithoutDeductionInput, Prisma.SavingUncheckedCreateWithoutDeductionInput>
}

export type SavingUpsertWithoutDeductionInput = {
  update: Prisma.XOR<Prisma.SavingUpdateWithoutDeductionInput, Prisma.SavingUncheckedUpdateWithoutDeductionInput>
  create: Prisma.XOR<Prisma.SavingCreateWithoutDeductionInput, Prisma.SavingUncheckedCreateWithoutDeductionInput>
  where?: Prisma.SavingWhereInput
}

export type SavingUpdateToOneWithWhereWithoutDeductionInput = {
  where?: Prisma.SavingWhereInput
  data: Prisma.XOR<Prisma.SavingUpdateWithoutDeductionInput, Prisma.SavingUncheckedUpdateWithoutDeductionInput>
}

export type SavingUpdateWithoutDeductionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutSavingsNestedInput
  loan?: Prisma.LoanUpdateOneWithoutSavingsNestedInput
  shortLoan?: Prisma.ShortLoanUpdateOneWithoutSavingsNestedInput
  penalty?: Prisma.PenaltyUpdateOneWithoutSavingsNestedInput
}

export type SavingUncheckedUpdateWithoutDeductionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavingCreateWithoutLoanInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutSavingsInput
  shortLoan?: Prisma.ShortLoanCreateNestedOneWithoutSavingsInput
  penalty?: Prisma.PenaltyCreateNestedOneWithoutSavingsInput
  deduction?: Prisma.DeductionCreateNestedOneWithoutSavingInput
}

export type SavingUncheckedCreateWithoutLoanInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  shortLoanId?: string | null
  penaltyId?: string | null
  memberId: string
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  deduction?: Prisma.DeductionUncheckedCreateNestedOneWithoutSavingInput
}

export type SavingCreateOrConnectWithoutLoanInput = {
  where: Prisma.SavingWhereUniqueInput
  create: Prisma.XOR<Prisma.SavingCreateWithoutLoanInput, Prisma.SavingUncheckedCreateWithoutLoanInput>
}

export type SavingCreateManyLoanInputEnvelope = {
  data: Prisma.SavingCreateManyLoanInput | Prisma.SavingCreateManyLoanInput[]
  skipDuplicates?: boolean
}

export type SavingUpsertWithWhereUniqueWithoutLoanInput = {
  where: Prisma.SavingWhereUniqueInput
  update: Prisma.XOR<Prisma.SavingUpdateWithoutLoanInput, Prisma.SavingUncheckedUpdateWithoutLoanInput>
  create: Prisma.XOR<Prisma.SavingCreateWithoutLoanInput, Prisma.SavingUncheckedCreateWithoutLoanInput>
}

export type SavingUpdateWithWhereUniqueWithoutLoanInput = {
  where: Prisma.SavingWhereUniqueInput
  data: Prisma.XOR<Prisma.SavingUpdateWithoutLoanInput, Prisma.SavingUncheckedUpdateWithoutLoanInput>
}

export type SavingUpdateManyWithWhereWithoutLoanInput = {
  where: Prisma.SavingScalarWhereInput
  data: Prisma.XOR<Prisma.SavingUpdateManyMutationInput, Prisma.SavingUncheckedUpdateManyWithoutLoanInput>
}

export type SavingCreateWithoutShortLoanInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutSavingsInput
  loan?: Prisma.LoanCreateNestedOneWithoutSavingsInput
  penalty?: Prisma.PenaltyCreateNestedOneWithoutSavingsInput
  deduction?: Prisma.DeductionCreateNestedOneWithoutSavingInput
}

export type SavingUncheckedCreateWithoutShortLoanInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  loanId?: string | null
  penaltyId?: string | null
  memberId: string
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  deduction?: Prisma.DeductionUncheckedCreateNestedOneWithoutSavingInput
}

export type SavingCreateOrConnectWithoutShortLoanInput = {
  where: Prisma.SavingWhereUniqueInput
  create: Prisma.XOR<Prisma.SavingCreateWithoutShortLoanInput, Prisma.SavingUncheckedCreateWithoutShortLoanInput>
}

export type SavingCreateManyShortLoanInputEnvelope = {
  data: Prisma.SavingCreateManyShortLoanInput | Prisma.SavingCreateManyShortLoanInput[]
  skipDuplicates?: boolean
}

export type SavingUpsertWithWhereUniqueWithoutShortLoanInput = {
  where: Prisma.SavingWhereUniqueInput
  update: Prisma.XOR<Prisma.SavingUpdateWithoutShortLoanInput, Prisma.SavingUncheckedUpdateWithoutShortLoanInput>
  create: Prisma.XOR<Prisma.SavingCreateWithoutShortLoanInput, Prisma.SavingUncheckedCreateWithoutShortLoanInput>
}

export type SavingUpdateWithWhereUniqueWithoutShortLoanInput = {
  where: Prisma.SavingWhereUniqueInput
  data: Prisma.XOR<Prisma.SavingUpdateWithoutShortLoanInput, Prisma.SavingUncheckedUpdateWithoutShortLoanInput>
}

export type SavingUpdateManyWithWhereWithoutShortLoanInput = {
  where: Prisma.SavingScalarWhereInput
  data: Prisma.XOR<Prisma.SavingUpdateManyMutationInput, Prisma.SavingUncheckedUpdateManyWithoutShortLoanInput>
}

export type SavingCreateWithoutPenaltyInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutSavingsInput
  loan?: Prisma.LoanCreateNestedOneWithoutSavingsInput
  shortLoan?: Prisma.ShortLoanCreateNestedOneWithoutSavingsInput
  deduction?: Prisma.DeductionCreateNestedOneWithoutSavingInput
}

export type SavingUncheckedCreateWithoutPenaltyInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  loanId?: string | null
  shortLoanId?: string | null
  memberId: string
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  deduction?: Prisma.DeductionUncheckedCreateNestedOneWithoutSavingInput
}

export type SavingCreateOrConnectWithoutPenaltyInput = {
  where: Prisma.SavingWhereUniqueInput
  create: Prisma.XOR<Prisma.SavingCreateWithoutPenaltyInput, Prisma.SavingUncheckedCreateWithoutPenaltyInput>
}

export type SavingCreateManyPenaltyInputEnvelope = {
  data: Prisma.SavingCreateManyPenaltyInput | Prisma.SavingCreateManyPenaltyInput[]
  skipDuplicates?: boolean
}

export type SavingUpsertWithWhereUniqueWithoutPenaltyInput = {
  where: Prisma.SavingWhereUniqueInput
  update: Prisma.XOR<Prisma.SavingUpdateWithoutPenaltyInput, Prisma.SavingUncheckedUpdateWithoutPenaltyInput>
  create: Prisma.XOR<Prisma.SavingCreateWithoutPenaltyInput, Prisma.SavingUncheckedCreateWithoutPenaltyInput>
}

export type SavingUpdateWithWhereUniqueWithoutPenaltyInput = {
  where: Prisma.SavingWhereUniqueInput
  data: Prisma.XOR<Prisma.SavingUpdateWithoutPenaltyInput, Prisma.SavingUncheckedUpdateWithoutPenaltyInput>
}

export type SavingUpdateManyWithWhereWithoutPenaltyInput = {
  where: Prisma.SavingScalarWhereInput
  data: Prisma.XOR<Prisma.SavingUpdateManyMutationInput, Prisma.SavingUncheckedUpdateManyWithoutPenaltyInput>
}

export type SavingCreateManyMemberInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  loanId?: string | null
  shortLoanId?: string | null
  penaltyId?: string | null
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SavingUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  loan?: Prisma.LoanUpdateOneWithoutSavingsNestedInput
  shortLoan?: Prisma.ShortLoanUpdateOneWithoutSavingsNestedInput
  penalty?: Prisma.PenaltyUpdateOneWithoutSavingsNestedInput
  deduction?: Prisma.DeductionUpdateOneWithoutSavingNestedInput
}

export type SavingUncheckedUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deduction?: Prisma.DeductionUncheckedUpdateOneWithoutSavingNestedInput
}

export type SavingUncheckedUpdateManyWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavingCreateManyLoanInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  shortLoanId?: string | null
  penaltyId?: string | null
  memberId: string
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SavingUpdateWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutSavingsNestedInput
  shortLoan?: Prisma.ShortLoanUpdateOneWithoutSavingsNestedInput
  penalty?: Prisma.PenaltyUpdateOneWithoutSavingsNestedInput
  deduction?: Prisma.DeductionUpdateOneWithoutSavingNestedInput
}

export type SavingUncheckedUpdateWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deduction?: Prisma.DeductionUncheckedUpdateOneWithoutSavingNestedInput
}

export type SavingUncheckedUpdateManyWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavingCreateManyShortLoanInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  loanId?: string | null
  penaltyId?: string | null
  memberId: string
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SavingUpdateWithoutShortLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutSavingsNestedInput
  loan?: Prisma.LoanUpdateOneWithoutSavingsNestedInput
  penalty?: Prisma.PenaltyUpdateOneWithoutSavingsNestedInput
  deduction?: Prisma.DeductionUpdateOneWithoutSavingNestedInput
}

export type SavingUncheckedUpdateWithoutShortLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deduction?: Prisma.DeductionUncheckedUpdateOneWithoutSavingNestedInput
}

export type SavingUncheckedUpdateManyWithoutShortLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  penaltyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavingCreateManyPenaltyInput = {
  id?: string
  amount: number
  mPesaRef?: string | null
  authorizedBy?: string | null
  loanId?: string | null
  shortLoanId?: string | null
  memberId: string
  status?: $Enums.TransactionStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SavingUpdateWithoutPenaltyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutSavingsNestedInput
  loan?: Prisma.LoanUpdateOneWithoutSavingsNestedInput
  shortLoan?: Prisma.ShortLoanUpdateOneWithoutSavingsNestedInput
  deduction?: Prisma.DeductionUpdateOneWithoutSavingNestedInput
}

export type SavingUncheckedUpdateWithoutPenaltyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deduction?: Prisma.DeductionUncheckedUpdateOneWithoutSavingNestedInput
}

export type SavingUncheckedUpdateManyWithoutPenaltyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  mPesaRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorizedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shortLoanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SavingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  amount?: boolean
  mPesaRef?: boolean
  authorizedBy?: boolean
  loanId?: boolean
  shortLoanId?: boolean
  penaltyId?: boolean
  memberId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Saving$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Saving$shortLoanArgs<ExtArgs>
  penalty?: boolean | Prisma.Saving$penaltyArgs<ExtArgs>
  deduction?: boolean | Prisma.Saving$deductionArgs<ExtArgs>
}, ExtArgs["result"]["saving"]>

export type SavingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  amount?: boolean
  mPesaRef?: boolean
  authorizedBy?: boolean
  loanId?: boolean
  shortLoanId?: boolean
  penaltyId?: boolean
  memberId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Saving$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Saving$shortLoanArgs<ExtArgs>
  penalty?: boolean | Prisma.Saving$penaltyArgs<ExtArgs>
}, ExtArgs["result"]["saving"]>

export type SavingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  amount?: boolean
  mPesaRef?: boolean
  authorizedBy?: boolean
  loanId?: boolean
  shortLoanId?: boolean
  penaltyId?: boolean
  memberId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Saving$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Saving$shortLoanArgs<ExtArgs>
  penalty?: boolean | Prisma.Saving$penaltyArgs<ExtArgs>
}, ExtArgs["result"]["saving"]>

export type SavingSelectScalar = {
  id?: boolean
  amount?: boolean
  mPesaRef?: boolean
  authorizedBy?: boolean
  loanId?: boolean
  shortLoanId?: boolean
  penaltyId?: boolean
  memberId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SavingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "amount" | "mPesaRef" | "authorizedBy" | "loanId" | "shortLoanId" | "penaltyId" | "memberId" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["saving"]>
export type SavingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Saving$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Saving$shortLoanArgs<ExtArgs>
  penalty?: boolean | Prisma.Saving$penaltyArgs<ExtArgs>
  deduction?: boolean | Prisma.Saving$deductionArgs<ExtArgs>
}
export type SavingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Saving$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Saving$shortLoanArgs<ExtArgs>
  penalty?: boolean | Prisma.Saving$penaltyArgs<ExtArgs>
}
export type SavingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
  loan?: boolean | Prisma.Saving$loanArgs<ExtArgs>
  shortLoan?: boolean | Prisma.Saving$shortLoanArgs<ExtArgs>
  penalty?: boolean | Prisma.Saving$penaltyArgs<ExtArgs>
}

export type $SavingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Saving"
  objects: {
    member: Prisma.$MemberPayload<ExtArgs>
    loan: Prisma.$LoanPayload<ExtArgs> | null
    shortLoan: Prisma.$ShortLoanPayload<ExtArgs> | null
    penalty: Prisma.$PenaltyPayload<ExtArgs> | null
    deduction: Prisma.$DeductionPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    amount: number
    mPesaRef: string | null
    authorizedBy: string | null
    loanId: string | null
    shortLoanId: string | null
    penaltyId: string | null
    memberId: string
    status: $Enums.TransactionStatus
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["saving"]>
  composites: {}
}

export type SavingGetPayload<S extends boolean | null | undefined | SavingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SavingPayload, S>

export type SavingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SavingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SavingCountAggregateInputType | true
  }

export interface SavingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Saving'], meta: { name: 'Saving' } }
  /**
   * Find zero or one Saving that matches the filter.
   * @param {SavingFindUniqueArgs} args - Arguments to find a Saving
   * @example
   * // Get one Saving
   * const saving = await prisma.saving.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SavingFindUniqueArgs>(args: Prisma.SelectSubset<T, SavingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SavingClient<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Saving that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SavingFindUniqueOrThrowArgs} args - Arguments to find a Saving
   * @example
   * // Get one Saving
   * const saving = await prisma.saving.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SavingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SavingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SavingClient<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Saving that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavingFindFirstArgs} args - Arguments to find a Saving
   * @example
   * // Get one Saving
   * const saving = await prisma.saving.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SavingFindFirstArgs>(args?: Prisma.SelectSubset<T, SavingFindFirstArgs<ExtArgs>>): Prisma.Prisma__SavingClient<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Saving that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavingFindFirstOrThrowArgs} args - Arguments to find a Saving
   * @example
   * // Get one Saving
   * const saving = await prisma.saving.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SavingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SavingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SavingClient<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Savings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Savings
   * const savings = await prisma.saving.findMany()
   * 
   * // Get first 10 Savings
   * const savings = await prisma.saving.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const savingWithIdOnly = await prisma.saving.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SavingFindManyArgs>(args?: Prisma.SelectSubset<T, SavingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Saving.
   * @param {SavingCreateArgs} args - Arguments to create a Saving.
   * @example
   * // Create one Saving
   * const Saving = await prisma.saving.create({
   *   data: {
   *     // ... data to create a Saving
   *   }
   * })
   * 
   */
  create<T extends SavingCreateArgs>(args: Prisma.SelectSubset<T, SavingCreateArgs<ExtArgs>>): Prisma.Prisma__SavingClient<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Savings.
   * @param {SavingCreateManyArgs} args - Arguments to create many Savings.
   * @example
   * // Create many Savings
   * const saving = await prisma.saving.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SavingCreateManyArgs>(args?: Prisma.SelectSubset<T, SavingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Savings and returns the data saved in the database.
   * @param {SavingCreateManyAndReturnArgs} args - Arguments to create many Savings.
   * @example
   * // Create many Savings
   * const saving = await prisma.saving.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Savings and only return the `id`
   * const savingWithIdOnly = await prisma.saving.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SavingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SavingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Saving.
   * @param {SavingDeleteArgs} args - Arguments to delete one Saving.
   * @example
   * // Delete one Saving
   * const Saving = await prisma.saving.delete({
   *   where: {
   *     // ... filter to delete one Saving
   *   }
   * })
   * 
   */
  delete<T extends SavingDeleteArgs>(args: Prisma.SelectSubset<T, SavingDeleteArgs<ExtArgs>>): Prisma.Prisma__SavingClient<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Saving.
   * @param {SavingUpdateArgs} args - Arguments to update one Saving.
   * @example
   * // Update one Saving
   * const saving = await prisma.saving.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SavingUpdateArgs>(args: Prisma.SelectSubset<T, SavingUpdateArgs<ExtArgs>>): Prisma.Prisma__SavingClient<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Savings.
   * @param {SavingDeleteManyArgs} args - Arguments to filter Savings to delete.
   * @example
   * // Delete a few Savings
   * const { count } = await prisma.saving.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SavingDeleteManyArgs>(args?: Prisma.SelectSubset<T, SavingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Savings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Savings
   * const saving = await prisma.saving.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SavingUpdateManyArgs>(args: Prisma.SelectSubset<T, SavingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Savings and returns the data updated in the database.
   * @param {SavingUpdateManyAndReturnArgs} args - Arguments to update many Savings.
   * @example
   * // Update many Savings
   * const saving = await prisma.saving.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Savings and only return the `id`
   * const savingWithIdOnly = await prisma.saving.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SavingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SavingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Saving.
   * @param {SavingUpsertArgs} args - Arguments to update or create a Saving.
   * @example
   * // Update or create a Saving
   * const saving = await prisma.saving.upsert({
   *   create: {
   *     // ... data to create a Saving
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Saving we want to update
   *   }
   * })
   */
  upsert<T extends SavingUpsertArgs>(args: Prisma.SelectSubset<T, SavingUpsertArgs<ExtArgs>>): Prisma.Prisma__SavingClient<runtime.Types.Result.GetResult<Prisma.$SavingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Savings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavingCountArgs} args - Arguments to filter Savings to count.
   * @example
   * // Count the number of Savings
   * const count = await prisma.saving.count({
   *   where: {
   *     // ... the filter for the Savings we want to count
   *   }
   * })
  **/
  count<T extends SavingCountArgs>(
    args?: Prisma.Subset<T, SavingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SavingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Saving.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SavingAggregateArgs>(args: Prisma.Subset<T, SavingAggregateArgs>): Prisma.PrismaPromise<GetSavingAggregateType<T>>

  /**
   * Group by Saving.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SavingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SavingGroupByArgs['orderBy'] }
      : { orderBy?: SavingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SavingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSavingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Saving model
 */
readonly fields: SavingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Saving.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SavingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  member<T extends Prisma.MemberDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MemberDefaultArgs<ExtArgs>>): Prisma.Prisma__MemberClient<runtime.Types.Result.GetResult<Prisma.$MemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  loan<T extends Prisma.Saving$loanArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Saving$loanArgs<ExtArgs>>): Prisma.Prisma__LoanClient<runtime.Types.Result.GetResult<Prisma.$LoanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  shortLoan<T extends Prisma.Saving$shortLoanArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Saving$shortLoanArgs<ExtArgs>>): Prisma.Prisma__ShortLoanClient<runtime.Types.Result.GetResult<Prisma.$ShortLoanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  penalty<T extends Prisma.Saving$penaltyArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Saving$penaltyArgs<ExtArgs>>): Prisma.Prisma__PenaltyClient<runtime.Types.Result.GetResult<Prisma.$PenaltyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  deduction<T extends Prisma.Saving$deductionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Saving$deductionArgs<ExtArgs>>): Prisma.Prisma__DeductionClient<runtime.Types.Result.GetResult<Prisma.$DeductionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Saving model
 */
export interface SavingFieldRefs {
  readonly id: Prisma.FieldRef<"Saving", 'String'>
  readonly amount: Prisma.FieldRef<"Saving", 'Float'>
  readonly mPesaRef: Prisma.FieldRef<"Saving", 'String'>
  readonly authorizedBy: Prisma.FieldRef<"Saving", 'String'>
  readonly loanId: Prisma.FieldRef<"Saving", 'String'>
  readonly shortLoanId: Prisma.FieldRef<"Saving", 'String'>
  readonly penaltyId: Prisma.FieldRef<"Saving", 'String'>
  readonly memberId: Prisma.FieldRef<"Saving", 'String'>
  readonly status: Prisma.FieldRef<"Saving", 'TransactionStatus'>
  readonly createdAt: Prisma.FieldRef<"Saving", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Saving", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Saving findUnique
 */
export type SavingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingInclude<ExtArgs> | null
  /**
   * Filter, which Saving to fetch.
   */
  where: Prisma.SavingWhereUniqueInput
}

/**
 * Saving findUniqueOrThrow
 */
export type SavingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingInclude<ExtArgs> | null
  /**
   * Filter, which Saving to fetch.
   */
  where: Prisma.SavingWhereUniqueInput
}

/**
 * Saving findFirst
 */
export type SavingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingInclude<ExtArgs> | null
  /**
   * Filter, which Saving to fetch.
   */
  where?: Prisma.SavingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Savings to fetch.
   */
  orderBy?: Prisma.SavingOrderByWithRelationInput | Prisma.SavingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Savings.
   */
  cursor?: Prisma.SavingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Savings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Savings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Savings.
   */
  distinct?: Prisma.SavingScalarFieldEnum | Prisma.SavingScalarFieldEnum[]
}

/**
 * Saving findFirstOrThrow
 */
export type SavingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingInclude<ExtArgs> | null
  /**
   * Filter, which Saving to fetch.
   */
  where?: Prisma.SavingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Savings to fetch.
   */
  orderBy?: Prisma.SavingOrderByWithRelationInput | Prisma.SavingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Savings.
   */
  cursor?: Prisma.SavingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Savings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Savings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Savings.
   */
  distinct?: Prisma.SavingScalarFieldEnum | Prisma.SavingScalarFieldEnum[]
}

/**
 * Saving findMany
 */
export type SavingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingInclude<ExtArgs> | null
  /**
   * Filter, which Savings to fetch.
   */
  where?: Prisma.SavingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Savings to fetch.
   */
  orderBy?: Prisma.SavingOrderByWithRelationInput | Prisma.SavingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Savings.
   */
  cursor?: Prisma.SavingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Savings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Savings.
   */
  skip?: number
  distinct?: Prisma.SavingScalarFieldEnum | Prisma.SavingScalarFieldEnum[]
}

/**
 * Saving create
 */
export type SavingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingInclude<ExtArgs> | null
  /**
   * The data needed to create a Saving.
   */
  data: Prisma.XOR<Prisma.SavingCreateInput, Prisma.SavingUncheckedCreateInput>
}

/**
 * Saving createMany
 */
export type SavingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Savings.
   */
  data: Prisma.SavingCreateManyInput | Prisma.SavingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Saving createManyAndReturn
 */
export type SavingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * The data used to create many Savings.
   */
  data: Prisma.SavingCreateManyInput | Prisma.SavingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Saving update
 */
export type SavingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingInclude<ExtArgs> | null
  /**
   * The data needed to update a Saving.
   */
  data: Prisma.XOR<Prisma.SavingUpdateInput, Prisma.SavingUncheckedUpdateInput>
  /**
   * Choose, which Saving to update.
   */
  where: Prisma.SavingWhereUniqueInput
}

/**
 * Saving updateMany
 */
export type SavingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Savings.
   */
  data: Prisma.XOR<Prisma.SavingUpdateManyMutationInput, Prisma.SavingUncheckedUpdateManyInput>
  /**
   * Filter which Savings to update
   */
  where?: Prisma.SavingWhereInput
  /**
   * Limit how many Savings to update.
   */
  limit?: number
}

/**
 * Saving updateManyAndReturn
 */
export type SavingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * The data used to update Savings.
   */
  data: Prisma.XOR<Prisma.SavingUpdateManyMutationInput, Prisma.SavingUncheckedUpdateManyInput>
  /**
   * Filter which Savings to update
   */
  where?: Prisma.SavingWhereInput
  /**
   * Limit how many Savings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Saving upsert
 */
export type SavingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingInclude<ExtArgs> | null
  /**
   * The filter to search for the Saving to update in case it exists.
   */
  where: Prisma.SavingWhereUniqueInput
  /**
   * In case the Saving found by the `where` argument doesn't exist, create a new Saving with this data.
   */
  create: Prisma.XOR<Prisma.SavingCreateInput, Prisma.SavingUncheckedCreateInput>
  /**
   * In case the Saving was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SavingUpdateInput, Prisma.SavingUncheckedUpdateInput>
}

/**
 * Saving delete
 */
export type SavingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingInclude<ExtArgs> | null
  /**
   * Filter which Saving to delete.
   */
  where: Prisma.SavingWhereUniqueInput
}

/**
 * Saving deleteMany
 */
export type SavingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Savings to delete
   */
  where?: Prisma.SavingWhereInput
  /**
   * Limit how many Savings to delete.
   */
  limit?: number
}

/**
 * Saving.loan
 */
export type Saving$loanArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Loan
   */
  select?: Prisma.LoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Loan
   */
  omit?: Prisma.LoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanInclude<ExtArgs> | null
  where?: Prisma.LoanWhereInput
}

/**
 * Saving.shortLoan
 */
export type Saving$shortLoanArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShortLoan
   */
  select?: Prisma.ShortLoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShortLoan
   */
  omit?: Prisma.ShortLoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortLoanInclude<ExtArgs> | null
  where?: Prisma.ShortLoanWhereInput
}

/**
 * Saving.penalty
 */
export type Saving$penaltyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penalty
   */
  select?: Prisma.PenaltySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penalty
   */
  omit?: Prisma.PenaltyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenaltyInclude<ExtArgs> | null
  where?: Prisma.PenaltyWhereInput
}

/**
 * Saving.deduction
 */
export type Saving$deductionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deduction
   */
  select?: Prisma.DeductionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deduction
   */
  omit?: Prisma.DeductionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeductionInclude<ExtArgs> | null
  where?: Prisma.DeductionWhereInput
}

/**
 * Saving without action
 */
export type SavingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Saving
   */
  select?: Prisma.SavingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Saving
   */
  omit?: Prisma.SavingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavingInclude<ExtArgs> | null
}
