import type { Metadata } from 'next'
import { Geist, Geist_Mono, Nunito, Nunito_Sans } from 'next/font/google'
import './globals.css'
import { SidebarProvider } from '../components/ui/sidebar'
import AppSidebar from '../components/layouts/appSidebar'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['latin'],
})

const nunitoSans = Nunito_Sans({
    variable: '--font-nunito-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${nunitoSans.variable} antialiased`}
            >
                <SidebarProvider>
                    <AppSidebar />
                    <main>{children}</main>
                </SidebarProvider>
            </body>
        </html>
    )
}
