import type { Metadata } from 'next'
import {
    Geist,
    Geist_Mono,
    Nunito,
    Nunito_Sans,
    Russo_One,
} from 'next/font/google'
import './globals.css'
import { SidebarProvider } from '../components/ui/sidebar'
import AppSidebar from '../components/layouts/appSidebar'
import Navbar from '../components/layouts/navbar'
import { ReactNode } from 'react'
import { Toaster } from '../components/ui/sonner'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['latin'],
})

const nunitoSans = Nunito_Sans({
    variable: '--font-nunito-mono',
    subsets: ['latin'],
})

const rusoOne = Russo_One({
    variable: '--font-russo-one',
    subsets: ['latin'],
    weight: '400',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }) => {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${nunitoSans.variable} ${rusoOne.variable} antialiased`}
            >
                <Toaster richColors theme='light' />
                <SidebarProvider className="w-full">
                    <AppSidebar />
                    <main className="space-y-4 w-full mt-2 px-5 font-nunito">
                        <Navbar />
                        {children}
                    </main>
                </SidebarProvider>
            </body>
        </html>
    )
}

export default RootLayout
