import type { Metadata } from 'next'
import {
    Geist,
    Geist_Mono,
    Nunito,
    Nunito_Sans,
    Russo_One,
} from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import NextTopLoader from 'nextjs-toploader'
import { Toaster } from '@/src/components/ui/sonner'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['latin'],
})

const nunitoSans = Nunito_Sans({
    variable: '--font-nunito-mono',
    subsets: ['latin'],
})

const rusoOne = Russo_One({
    variable: '--font-russo-one',
    subsets: ['latin'],
    weight: '400',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }) => {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${nunitoSans.variable} ${rusoOne.variable} antialiased`}
            >
                <NextTopLoader color='purple' height={1} />
                <Toaster richColors theme="light" />
                {children}
            </body>
        </html>
    )
}

export default RootLayout
